/**
 * Données réelles Booking.com — Atins (Lençóis Maranhenses)
 * Recherche MCP effectuée le 11/05/2026
 * Ancre : Casa LuMar · 352 €/nuit · 0★ · note 9.8
 * Dates : 09/08/2026 → 11/08/2026 (2 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * Note : price.book du MCP = prix TOTAL (2 nuits) → divisé par 2 pour obtenir le prix/nuit
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const ATINS_RESULTS: SearchResults = {
  nights: 2,
  searchedAt: '2026-05-11T12:20:00Z',
  isMock: false,

  anchor: {
    name: 'Casa LuMar',
    destination: 'Atins',
    checkinDate: '2026-08-09',
    checkoutDate: '2026-08-11',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/casa-lumar-atins.fr.html',
    pricePerNight: 352,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.8,
    services: [],
    vfmScore: 62,
    nights: 2,
    totalPrice: 704,
    lat: -2.572,
    lng: -42.747,
    address: 'Atins Maranhão, Atins',
    reviewCount: 5,
    facilities: ['parking', 'pool', 'wifi'],
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '13945070',
      name: 'Morada das Dunas',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 58,
      pricePerNight: 181,
      totalPrice: 362,
      nights: 2,
      currency: 'EUR',
      address: 'Atins, Maranhão',
      lat: -2.5680,
      lng: -42.7420,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=13945070&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 76,
      anchorVfmScore: 62,
      priceVsAnchor: -48.6,
      scoreVsAnchor: -1.0,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '6210031',
      name: 'Maré de Atins Eco Lodge',
      stars: 4,
      bookingScore: 8.6,
      reviewCount: 423,
      pricePerNight: 143,
      totalPrice: 286,
      nights: 2,
      currency: 'EUR',
      address: 'Rua da Alegria s/n, Atins',
      lat: -2.572319,
      lng: -42.747999,
      bookingUrl: 'https://www.booking.com/hotel/br/mare-de-atins-eco-lodge.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 76,
      anchorVfmScore: 62,
      priceVsAnchor: -59.4,
      scoreVsAnchor: -1.2,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '8354015',
      name: 'Pousada do Beto',
      stars: 3,
      bookingScore: 9.2,
      reviewCount: 110,
      pricePerNight: 155,
      totalPrice: 310,
      nights: 2,
      currency: 'EUR',
      address: 'Rua da Esperança, Santo Inácio, Atins',
      lat: -2.577522,
      lng: -42.751777,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-do-beto-barreirinhas12.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 76,
      anchorVfmScore: 62,
      priceVsAnchor: -56.0,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '12469036',
      name: 'Vila Monan',
      stars: 3,
      bookingScore: 9.1,
      reviewCount: 74,
      pricePerNight: 169,
      totalPrice: 338,
      nights: 2,
      currency: 'EUR',
      address: 'Rua do Porto, sem número, Vila Monan, Atins',
      lat: -2.574515,
      lng: -42.744457,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-monan.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 75,
      anchorVfmScore: 62,
      priceVsAnchor: -52.0,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '6180534',
      name: 'Casa Branca',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 34,
      pricePerNight: 122,
      totalPrice: 244,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Principal S/N, Alto do Atins',
      lat: -2.57085,
      lng: -42.743972,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-branca-barreirinhas12.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 71,
      anchorVfmScore: 62,
      priceVsAnchor: -65.3,
      scoreVsAnchor: -1.9,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '3090038',
      name: 'Pousada Vettore',
      stars: 3,
      bookingScore: 7.3,
      reviewCount: 56,
      pricePerNight: 157,
      totalPrice: 314,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Nova 03, Atins',
      lat: -2.571605,
      lng: -42.739193,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vettore.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 62,
      priceVsAnchor: -55.4,
      scoreVsAnchor: -2.5,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '8839336',
      name: 'Pousada Solar Maia Costa',
      stars: 3,
      bookingScore: 9.8,
      reviewCount: 308,
      pricePerNight: 303,
      totalPrice: 606,
      nights: 2,
      currency: 'EUR',
      address: 'Atins, Maranhão',
      lat: -2.5710,
      lng: -42.7470,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=8839336&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 62,
      priceVsAnchor: -13.9,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '8917563',
      name: 'Sky Atins Rooftop',
      stars: 4,
      bookingScore: 8.9,
      reviewCount: 123,
      pricePerNight: 328,
      totalPrice: 656,
      nights: 2,
      currency: 'EUR',
      address: 'Atins',
      lat: -2.570082,
      lng: -42.742263,
      bookingUrl: 'https://www.booking.com/hotel/br/sky-atins-rooftop-atins-barreirinhas.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 62,
      priceVsAnchor: -6.8,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '734750',
      name: 'Pousada Mirage Atins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 113,
      totalPrice: 226,
      nights: 2,
      currency: 'EUR',
      address: 'Rua projetada, s/n, Atins',
      lat: -2.569586,
      lng: -42.739994,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-mirage-atins.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 62,
      priceVsAnchor: -67.9,
      scoreVsAnchor: -9.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '9383519',
      name: 'Jandaia Atins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 223,
      totalPrice: 446,
      nights: 2,
      currency: 'EUR',
      address: 'Alto da Rua Principal, s/n, Atins',
      lat: -2.571786,
      lng: -42.745435,
      bookingUrl: 'https://www.booking.com/hotel/br/jandaia-barreirinhas.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 24,
      anchorVfmScore: 62,
      priceVsAnchor: -36.6,
      scoreVsAnchor: -9.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
