/**
 * Données réelles Booking.com — Atins
 * Recherche MCP effectuée le 16/05/2026
 * Ancre : Casa LuMar · 352 €/nuit · 0★ · note 9.8
 * Dates : 2026-08-09 → 2026-08-11 (2 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const ATINS_RESULTS: SearchResults = {
  nights: 2,
  searchedAt: '2026-05-16T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Casa LuMar',
    destination: 'Atins',
    checkinDate: '2026-08-09',
    checkoutDate: '2026-08-11',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/casa-lumar-atins.fr.html',
    pricePerNight: 352,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.8,
    services: [],
    vfmScore: 62,
    nights: 2,
    totalPrice: 704,
    lat: -2.572,
    lng: -42.747,
    address: 'Atins Maranhão, Atins',
    reviewCount: 5,
    facilities: ['parking', 'pool', 'wifi'],
  },

  alternatives: [
    {
      id: '8839336',
      name: 'Pousada Solar Maia Costa',
      stars: 3,
      bookingScore: 9.8,
      reviewCount: 308,
      pricePerNight: 295.70,
      totalPrice: 591.41,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Beira Mar, s/n, Atins',
      lat: -2.56934,
      lng: -42.744977,
      bookingUrl: 'https://www.booking.com/hotel/br/solar-maia-costa.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 62,
      priceVsAnchor: -16.0,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '8917563',
      name: 'Sky Atins Rooftop',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 123,
      pricePerNight: 320.68,
      totalPrice: 641.36,
      nights: 2,
      currency: 'EUR',
      address: 'Atins',
      lat: -2.570082,
      lng: -42.742263,
      bookingUrl: 'https://www.booking.com/hotel/br/sky-atins-rooftop-atins-barreirinhas.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'breakfast', 'parking', 'pool', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 62,
      priceVsAnchor: -8.9,
      scoreVsAnchor: -1.0,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14554561',
      name: 'Chalé Átina - Atins',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 3,
      pricePerNight: 279.79,
      totalPrice: 559.58,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Principal, Condomínio Village Buna Atins, casa 19',
      lat: -2.579106,
      lng: -42.754921,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-atina-barreirinhas2.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 62,
      priceVsAnchor: -20.5,
      scoreVsAnchor: -1.1,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '2145622',
      name: 'Convento Arcádia',
      stars: 4,
      bookingScore: 9.0,
      reviewCount: 47,
      pricePerNight: 383.42,
      totalPrice: 766.84,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Esperança, 3',
      lat: -2.569844,
      lng: -42.742434,
      bookingUrl: 'https://www.booking.com/hotel/br/convento-arcadia.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 62,
      priceVsAnchor: 8.9,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '8377459',
      name: 'Alto Bonito - Atins',
      stars: 3,
      bookingScore: 8.3,
      reviewCount: 94,
      pricePerNight: 274.87,
      totalPrice: 549.74,
      nights: 2,
      currency: 'EUR',
      address: 'Rua da Saudade SN',
      lat: -2.571663,
      lng: -42.749336,
      bookingUrl: 'https://www.booking.com/hotel/br/alto-bonito-atins1.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 62,
      priceVsAnchor: -21.9,
      scoreVsAnchor: -1.5,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '4218354',
      name: 'Casa de Maria na Praia de Atins',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 5,
      pricePerNight: 338.50,
      totalPrice: 676.99,
      nights: 2,
      currency: 'EUR',
      address: 'Atins Avenida Principal s/n',
      lat: -2.570462,
      lng: -42.742855,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-de-maria-na-praia-de-atins.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 62,
      priceVsAnchor: -3.8,
      scoreVsAnchor: -1.4,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14802777',
      name: 'Trino do Maro - Atins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 279.96,
      totalPrice: 559.92,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Projetada, cond. Atins Ville Lençóis, casa 7',
      lat: -2.574152,
      lng: -42.745764,
      bookingUrl: 'https://www.booking.com/hotel/br/trino-do-maro.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 62,
      priceVsAnchor: -20.5,
      scoreVsAnchor: -9.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '9383519',
      name: 'Jandaia Atins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 287.36,
      totalPrice: 574.71,
      nights: 2,
      currency: 'EUR',
      address: 'Alto da Rua Principal, s/n, Atins',
      lat: -2.571786,
      lng: -42.745435,
      bookingUrl: 'https://www.booking.com/hotel/br/jandaia-barreirinhas.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 62,
      priceVsAnchor: -18.4,
      scoreVsAnchor: -9.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '7217368',
      name: 'POUSADA IRMAOS ATINS',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 306.09,
      totalPrice: 612.18,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Principal, Vila de Atins, Maranhão',
      lat: -2.570904,
      lng: -42.743916,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-irmaos-atins.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 62,
      priceVsAnchor: -13.0,
      scoreVsAnchor: -9.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '3151342',
      name: 'Pousada Maresia',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 381.25,
      totalPrice: 762.50,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Principal, s/n',
      lat: -2.569918,
      lng: -42.747898,
      bookingUrl: 'https://www.booking.com/hotel/br/maresia-atins.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 62,
      priceVsAnchor: 8.3,
      scoreVsAnchor: -9.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
