/**
 * Données réelles Booking.com — Atins
 * Recherche MCP effectuée le 04/07/2026
 * Ancre : Casa LuMar · 352 €/nuit · 0★ · note 9.8
 * Dates : 2026-08-09 → 2026-08-11 (2 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const ATINS_RESULTS: SearchResults = {
  nights: 2,
  searchedAt: '2026-07-04T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Casa LuMar',
    destination: 'Atins',
    checkinDate: '2026-08-09',
    checkoutDate: '2026-08-11',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/casa-lumar-atins.fr.html',
    pricePerNight: 352,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.8,
    services: [],
    vfmScore: 62,
    nights: 2,
    totalPrice: 704,
    lat: -2.572,
    lng: -42.747,
    address: 'Atins Maranhão, Atins',
    reviewCount: 5,
    facilities: ['parking', 'pool', 'wifi'],
  },

  alternatives: [
    {
      id: '7791470',
      name: 'Limbo Atins Chalets',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 125,
      pricePerNight: 173.61,
      totalPrice: 347.22,
      nights: 2,
      currency: 'EUR',
      address: 'Atins, Maranhão',
      lat: -2.570321,
      lng: -42.74822,
      bookingUrl: 'https://www.booking.com/hotel/br/limbo-atins-chalet-mar-includes-breakfast.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'airport_shuttle'],
      isAvailable: true,
      vfmScore: 79,
      anchorVfmScore: 62,
      priceVsAnchor: -51,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '12574159',
      name: 'Amar é Atins',
      stars: 3,
      bookingScore: 9.8,
      reviewCount: 7,
      pricePerNight: 159.67,
      totalPrice: 319.34,
      nights: 2,
      currency: 'EUR',
      address: 'Rua Principal S/n Santo Inácio',
      lat: -2.578038,
      lng: -42.75043,
      bookingUrl: 'https://www.booking.com/hotel/br/amar-e-atins-barreirinhas.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'parking', 'sea_view'],
      isAvailable: true,
      vfmScore: 78,
      anchorVfmScore: 62,
      priceVsAnchor: -55,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '12469036',
      name: 'Vila Monan',
      stars: 3,
      bookingScore: 8.9,
      reviewCount: 87,
      pricePerNight: 155.11,
      totalPrice: 310.22,
      nights: 2,
      currency: 'EUR',
      address: 'Atins, Maranhão',
      lat: -2.574515,
      lng: -42.744457,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-monan.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'parking'],
      isAvailable: true,
      vfmScore: 75,
      anchorVfmScore: 62,
      priceVsAnchor: -56,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '13047142',
      name: 'Canto do Mar',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 33,
      pricePerNight: 236.55,
      totalPrice: 473.10,
      nights: 2,
      currency: 'EUR',
      address: 'Atins, Maranhão',
      lat: -2.569162,
      lng: -42.749973,
      bookingUrl: 'https://www.booking.com/hotel/br/canto-do-mar-atins-lencois-maranhenses.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'parking', 'sea_view'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 62,
      priceVsAnchor: -33,
      scoreVsAnchor: -1.1,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '4218354',
      name: 'Casa de Maria na Praia de Atins',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 5,
      pricePerNight: 283.02,
      totalPrice: 566.03,
      nights: 2,
      currency: 'EUR',
      address: 'Atins Avenida Principal s/n',
      lat: -2.570462,
      lng: -42.742855,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-de-maria-na-praia-de-atins.html?aid=8132308&checkin=2026-08-09&checkout=2026-08-11&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'parking', 'sea_view'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 62,
      priceVsAnchor: -20,
      scoreVsAnchor: -1.4,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
  ],
};
