/**
 * Données réelles Booking.com — Barreirinhas (Lençóis Maranhenses)
 * Recherche MCP effectuée le 11/05/2026
 * Ancre : Pousada do Buriti · 289 €/nuit · 0★ · note 9.1
 * Dates : 08/08/2026 → 09/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const BARREIRINHAS_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-11T12:10:00Z',
  isMock: false,

  anchor: {
    name: 'Pousada do Buriti',
    destination: 'Barreirinhas',
    checkinDate: '2026-08-08',
    checkoutDate: '2026-08-09',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-do-buriti.fr.html',
    pricePerNight: 289,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.1,
    services: [],
    vfmScore: 58,
    nights: 1,
    totalPrice: 289,
    lat: -2.754,
    lng: -42.823,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '1688000',
      name: 'Chalé Porto dos Lençóis',
      stars: 3,
      bookingScore: 9.4,
      reviewCount: 110,
      pricePerNight: 116,
      totalPrice: 116,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7480,
      lng: -42.8150,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=1688000&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 77,
      anchorVfmScore: 58,
      priceVsAnchor: -59.9,
      scoreVsAnchor: 0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '4860819',
      name: 'Recanto das Arvores',
      stars: 4,
      bookingScore: 8.3,
      reviewCount: 612,
      pricePerNight: 114,
      totalPrice: 114,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7520,
      lng: -42.8190,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=4860819&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 75,
      anchorVfmScore: 58,
      priceVsAnchor: -60.6,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '11482931',
      name: 'Pousada Viva Vida',
      stars: 3,
      bookingScore: 9.0,
      reviewCount: 186,
      pricePerNight: 128,
      totalPrice: 128,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7560,
      lng: -42.8270,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=11482931&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 75,
      anchorVfmScore: 58,
      priceVsAnchor: -55.7,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '11398627',
      name: 'Espaço Augusto',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 102,
      pricePerNight: 108,
      totalPrice: 108,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7490,
      lng: -42.8210,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=11398627&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 74,
      anchorVfmScore: 58,
      priceVsAnchor: -62.6,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '302965',
      name: 'Orla Nautica',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 156,
      pricePerNight: 240,
      totalPrice: 240,
      nights: 1,
      currency: 'EUR',
      address: 'Beira Rio, Barreirinhas',
      lat: -2.7600,
      lng: -42.8290,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=302965&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: -17.0,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '9400580',
      name: 'Apartamento Lençóis Confort',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 111,
      totalPrice: 111,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7530,
      lng: -42.8230,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=9400580&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 58,
      priceVsAnchor: -61.6,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '7302093',
      name: 'Pousada Brilho dos Lençóis',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 117,
      totalPrice: 117,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7510,
      lng: -42.8180,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=7302093&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 58,
      priceVsAnchor: -59.5,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '274041',
      name: 'Pousada Boa Vista',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 144,
      totalPrice: 144,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7470,
      lng: -42.8160,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=274041&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 58,
      priceVsAnchor: -50.2,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '2660139',
      name: 'Pousada Lins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 141,
      totalPrice: 141,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7540,
      lng: -42.8240,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=2660139&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 58,
      priceVsAnchor: -51.2,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '2535251',
      name: 'Pousada Vilas Boas',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 144,
      totalPrice: 144,
      nights: 1,
      currency: 'EUR',
      address: 'Barreirinhas, Maranhão',
      lat: -2.7550,
      lng: -42.8260,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=2535251&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 58,
      priceVsAnchor: -50.2,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
  ],
};
