/**
 * Données réelles Booking.com — Barreirinhas (Lençóis Maranhenses)
 * Recherche MCP effectuée le 14/05/2026
 * Ancre : Pousada do Buriti · 289 €/nuit · 0★ · note 9.1
 * Dates : 2026-08-08 → 2026-08-09 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const BARREIRINHAS_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-14T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pousada do Buriti',
    destination: 'Barreirinhas',
    checkinDate: '2026-08-08',
    checkoutDate: '2026-08-09',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-do-buriti.fr.html',
    pricePerNight: 289,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.1,
    services: [],
    vfmScore: 58,
    nights: 1,
    totalPrice: 289,
    lat: -2.752914,
    lng: -42.828033,
    address: 'Rua Inácio Lins. S/N, Barreirinhas',
    reviewCount: 0,
    facilities: ['ac', 'pool', 'restaurant', 'wifi'],
  },

  alternatives: [
    {
      id: '14630843',
      name: 'Lar dos Lençóis BHS',
      stars: 3,
      bookingScore: 9.9,
      reviewCount: 80,
      pricePerNight: 219.76,
      totalPrice: 219.76,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Domingos Carvalho-Murici Prédio',
      lat: -2.752689,
      lng: -42.832601,
      bookingUrl: 'https://www.booking.com/hotel/br/diaria-quarto.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 58,
      priceVsAnchor: -23.9,
      scoreVsAnchor: 0.8,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '11274841',
      name: 'POUSADA PARAÍSO CULTURAL',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 135,
      pricePerNight: 219.07,
      totalPrice: 219.07,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Cazuza Ramos,550',
      lat: -2.747095,
      lng: -42.828368,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-paraiso-cultural-barreirinhas1.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 58,
      priceVsAnchor: -24.2,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '302965',
      name: 'Orla Nautica',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 157,
      pricePerNight: 240.49,
      totalPrice: 240.49,
      nights: 1,
      currency: 'EUR',
      address: 'Sitio Cantinho S/N, Carnaubal',
      lat: -2.739276,
      lng: -42.834763,
      bookingUrl: 'https://www.booking.com/hotel/br/park-nautico.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: -16.8,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '1979231',
      name: 'Casa Vilar Rio Lençois',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 43,
      pricePerNight: 222.89,
      totalPrice: 222.89,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Domingos Carvalho, N° 58, Bairro Murici',
      lat: -2.754715,
      lng: -42.834863,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-temporada-barreirinhas-lencois-maranhenses.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 58,
      priceVsAnchor: -22.9,
      scoreVsAnchor: -1.2,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '274041',
      name: 'Pousada Boa Vista',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 220.16,
      totalPrice: 220.16,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Mangue Alto S/N',
      lat: -2.740081,
      lng: -42.795291,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-boa-vista.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 58,
      priceVsAnchor: -23.8,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '13082025',
      name: "Charme D'Maria Pousada",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 222.01,
      totalPrice: 222.01,
      nights: 1,
      currency: 'EUR',
      address: 'Rua nova, s/nº - Centro - Barreirinhas, MA',
      lat: -2.746327,
      lng: -42.827804,
      bookingUrl: 'https://www.booking.com/hotel/br/charme-d-maria-pousada-barreirinhas.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 58,
      priceVsAnchor: -23.2,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '15918578',
      name: 'Hotel Dunas e Lençóis',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 235.76,
      totalPrice: 235.76,
      nights: 1,
      currency: 'EUR',
      address: 'R. São José, 1234',
      lat: -2.762929,
      lng: -42.833099,
      bookingUrl: 'https://www.booking.com/hotel/br/dunas-e-lencois.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 58,
      priceVsAnchor: -18.4,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '2660139',
      name: 'Pousada Lins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 248.63,
      totalPrice: 248.63,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Joaquim Soeiro de Carvalho 550 - Centro',
      lat: -2.750369,
      lng: -42.827031,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-lins.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['pool', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 58,
      priceVsAnchor: -14.0,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '15478157',
      name: 'Lençóis Prime Hotel Barreirinhas',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 351.76,
      totalPrice: 351.76,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Sertãozinho',
      lat: -2.753844,
      lng: -42.80205,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-barreiras-barreirinhas.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 58,
      priceVsAnchor: 21.7,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
