/**
 * Données réelles Booking.com — Barreirinhas (Lençóis Maranhenses)
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Pousada do Buriti · 289 €/nuit · 0★ · note 9.1
 * Dates : 2026-08-08 → 2026-08-09 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const BARREIRINHAS_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pousada do Buriti',
    destination: 'Barreirinhas',
    checkinDate: '2026-08-08',
    checkoutDate: '2026-08-09',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-do-buriti.fr.html',
    pricePerNight: 289,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.1,
    services: [],
    vfmScore: 58,
    nights: 1,
    totalPrice: 289,
    lat: -2.752914,
    lng: -42.828033,
    address: 'Rua Inácio Lins. S/N, Barreirinhas',
    reviewCount: 0,
    facilities: ['parking', 'pool', 'restaurant', 'wifi'],
  },

  alternatives: [
    {
      id: '14488408',
      name: 'Lençóis House',
      stars: 4,
      bookingScore: 9.8,
      reviewCount: 14,
      pricePerNight: 219.68,
      totalPrice: 219.68,
      nights: 1,
      currency: 'EUR',
      address: 'Estrada Sem Nome 65590-000',
      lat: -2.78651,
      lng: -42.843265,
      bookingUrl: 'https://www.booking.com/hotel/br/lencois-house.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 71,
      anchorVfmScore: 58,
      priceVsAnchor: -24.0,
      scoreVsAnchor: 0.7,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '13122242',
      name: 'Pousada Villa Monale',
      stars: 5,
      bookingScore: 9.7,
      reviewCount: 22,
      pricePerNight: 253.51,
      totalPrice: 253.51,
      nights: 1,
      currency: 'EUR',
      address: 'MA-315',
      lat: -2.771185,
      lng: -42.836427,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-villa-monale.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 71,
      anchorVfmScore: 58,
      priceVsAnchor: -12.3,
      scoreVsAnchor: 0.6,
      starsVsAnchor: 5,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '367644',
      name: 'Porto Preguiças Resort',
      stars: 5,
      bookingScore: 9.4,
      reviewCount: 1850,
      pricePerNight: 358.81,
      totalPrice: 358.81,
      nights: 1,
      currency: 'EUR',
      address: 'Estrada do Carnaubal, s/n',
      lat: -2.737815,
      lng: -42.837574,
      bookingUrl: 'https://www.booking.com/hotel/br/porto-preguiassas-resort.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['airport_shuttle', 'gym', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 58,
      priceVsAnchor: 24.2,
      scoreVsAnchor: 0.3,
      starsVsAnchor: 5,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '11274841',
      name: 'POUSADA PARAÍSO CULTURAL',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 137,
      pricePerNight: 215.82,
      totalPrice: 215.82,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Cazuza Ramos 550',
      lat: -2.747095,
      lng: -42.828368,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-paraiso-cultural-barreirinhas1.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 58,
      priceVsAnchor: -25.3,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '302965',
      name: 'Orla Nautica',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 164,
      pricePerNight: 236.93,
      totalPrice: 236.93,
      nights: 1,
      currency: 'EUR',
      address: 'Sitio Cantinho S/N, Carnaubal',
      lat: -2.739276,
      lng: -42.834763,
      bookingUrl: 'https://www.booking.com/hotel/br/park-nautico.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: -18.0,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '1979231',
      name: 'Casa Vilar Rio Lençois Maranhenses',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 43,
      pricePerNight: 219.59,
      totalPrice: 219.59,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Domingos Carvalho 58',
      lat: -2.754715,
      lng: -42.834863,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-vilar-rio-lencois-maranhenses.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 58,
      priceVsAnchor: -24.0,
      scoreVsAnchor: -1.2,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '15918578',
      name: 'Hotel Dunas e Lençóis',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 232.27,
      totalPrice: 232.27,
      nights: 1,
      currency: 'EUR',
      address: 'R São José 1234',
      lat: -2.762929,
      lng: -42.833099,
      bookingUrl: 'https://www.booking.com/hotel/br/dunas-e-lencois.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 58,
      priceVsAnchor: -19.6,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '13082025',
      name: "Charme D'Maria Pousada",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 238.07,
      totalPrice: 238.07,
      nights: 1,
      currency: 'EUR',
      address: 'Rua nova s/nº Centro',
      lat: -2.746327,
      lng: -42.827804,
      bookingUrl: 'https://www.booking.com/hotel/br/charme-d-maria-pousada-barreirinhas.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 58,
      priceVsAnchor: -17.6,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '2660139',
      name: 'Pousada Lins',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 244.94,
      totalPrice: 244.94,
      nights: 1,
      currency: 'EUR',
      address: 'Av Joaquim Soeiro de Carvalho 550',
      lat: -2.750369,
      lng: -42.827031,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-lins.html?aid=8132308&checkin=2026-08-08&checkout=2026-08-09&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 58,
      priceVsAnchor: -15.2,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
