/**
 * Données réelles Booking.com — Ilha de Boipeba
 * Recherche MCP effectuée le 04/07/2026
 * Ancre : Pouso da Maré · 143 €/nuit · 0★ · note 9.1
 * Dates : 2026-08-18 → 2026-08-21 (3 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const BOIPEBA_RESULTS: SearchResults = {
  nights: 3,
  searchedAt: '2026-07-04T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pouso da Maré',
    destination: 'Ilha de Boipeba',
    checkinDate: '2026-08-18',
    checkoutDate: '2026-08-21',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-pouso-da-mare.fr.html',
    pricePerNight: 143,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.1,
    services: [],
    vfmScore: 58,
    nights: 3,
    totalPrice: 429,
    lat: -13.580,
    lng: -38.925,
    address: 'Rua da Praia, 58, Île de Boipeba',
    reviewCount: 242,
    facilities: ['breakfast', 'sea_view', 'spa', 'wifi'],
  },

  alternatives: [
    {
      id: '9662806',
      name: 'Saudade da Bahia',
      stars: 4,
      bookingScore: 9.7,
      reviewCount: 42,
      pricePerNight: 70.12,
      totalPrice: 210.36,
      nights: 3,
      currency: 'EUR',
      address: 'Moreré, Ilha de Boipeba',
      lat: -13.610484,
      lng: -38.906979,
      bookingUrl: 'https://www.booking.com/hotel/br/saudade-da-bahia.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'sea_view', 'sea_view'],
      isAvailable: true,
      vfmScore: 81,
      anchorVfmScore: 58,
      priceVsAnchor: -51,
      scoreVsAnchor: 0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '9154138',
      name: 'Pousada Vila Palma Boipeba',
      stars: 4,
      bookingScore: 8.9,
      reviewCount: 277,
      pricePerNight: 76.37,
      totalPrice: 229.12,
      nights: 3,
      currency: 'EUR',
      address: 'Praia Boca da Barra 07',
      lat: -13.579573,
      lng: -38.927073,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vila-palma-cairu1.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'sea_view'],
      isAvailable: true,
      vfmScore: 76,
      anchorVfmScore: 58,
      priceVsAnchor: -47,
      scoreVsAnchor: -0.2,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '1518334',
      name: 'Pousada Vila da Barra',
      stars: 4,
      bookingScore: 9.5,
      reviewCount: 110,
      pricePerNight: 99.22,
      totalPrice: 297.66,
      nights: 3,
      currency: 'EUR',
      address: 'Boca da Barra, Ilha de Boipeba',
      lat: -13.580642,
      lng: -38.927672,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vila-da-barra.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'sea_view'],
      isAvailable: true,
      vfmScore: 72,
      anchorVfmScore: 58,
      priceVsAnchor: -31,
      scoreVsAnchor: 0.4,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '1194624',
      name: 'Casa Aiti',
      stars: 4,
      bookingScore: 9.7,
      reviewCount: 111,
      pricePerNight: 101.89,
      totalPrice: 305.66,
      nights: 3,
      currency: 'EUR',
      address: 'Boca da Barra, Ilha de Boipeba',
      lat: -13.580058,
      lng: -38.925786,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-da-cris-ilha-de-boipeba.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'sea_view', 'airport_shuttle'],
      isAvailable: true,
      vfmScore: 72,
      anchorVfmScore: 58,
      priceVsAnchor: -29,
      scoreVsAnchor: 0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '268602',
      name: 'Alizées Moreré',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 315,
      pricePerNight: 109.49,
      totalPrice: 328.47,
      nights: 3,
      currency: 'EUR',
      address: 'Moreré, Ilha de Boipeba',
      lat: -13.608793,
      lng: -38.906062,
      bookingUrl: 'https://www.booking.com/hotel/br/alizees-morere.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'sea_view'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 58,
      priceVsAnchor: -23,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '578323',
      name: 'Mangueira Boutique Hotel Moreré',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 62,
      pricePerNight: 128.59,
      totalPrice: 385.76,
      nights: 3,
      currency: 'EUR',
      address: 'Moreré, Ilha de Boipeba',
      lat: -13.609853,
      lng: -38.907582,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-a-mangueira.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'sea_view', 'airport_shuttle'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 58,
      priceVsAnchor: -10,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
  ],
};
