/**
 * Données réelles Booking.com — Ilha de Boipeba
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Pouso da Maré · 143 €/nuit · 0★ · note 9.1
 * Dates : 2026-08-18 → 2026-08-21 (3 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const BOIPEBA_RESULTS: SearchResults = {
  nights: 3,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pouso da Maré',
    destination: 'Ilha de Boipeba',
    checkinDate: '2026-08-18',
    checkoutDate: '2026-08-21',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-pouso-da-mare.fr.html',
    pricePerNight: 143,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.1,
    services: [],
    vfmScore: 58,
    nights: 3,
    totalPrice: 429,
    lat: -13.580,
    lng: -38.925,
    address: 'Rua da Praia, 58, Île de Boipeba',
    reviewCount: 242,
    facilities: ['breakfast', 'sea_view', 'spa', 'wifi'],
  },

  alternatives: [
    {
      id: '9154138',
      name: 'Pousada Vila Palma Boipeba',
      stars: 4,
      bookingScore: 8.9,
      reviewCount: 273,
      pricePerNight: 108.39,
      totalPrice: 325.17,
      nights: 3,
      currency: 'EUR',
      address: 'Praia Boca da Barra 07',
      lat: -13.579573,
      lng: -38.927073,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vila-palma-cairu1.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 58,
      priceVsAnchor: -24.2,
      scoreVsAnchor: -0.2,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '907149',
      name: 'Pousada Casa da Edinha',
      stars: 3,
      bookingScore: 9.9,
      reviewCount: 85,
      pricePerNight: 116.10,
      totalPrice: 348.29,
      nights: 3,
      currency: 'EUR',
      address: 'Rua do Ipiranga, 4',
      lat: -13.585551,
      lng: -38.925505,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-casa-da-edinha.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 58,
      priceVsAnchor: -18.8,
      scoreVsAnchor: 0.8,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '13460835',
      name: 'Pousada Feliz Boipeba',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 27,
      pricePerNight: 141.42,
      totalPrice: 424.25,
      nights: 3,
      currency: 'EUR',
      address: 'Rua do Porto',
      lat: -13.58221,
      lng: -38.928826,
      bookingUrl: 'https://www.booking.com/hotel/br/villages-feliz-boipeba.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 58,
      priceVsAnchor: -1.1,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '8434580',
      name: 'Pousada Moreré',
      stars: 3,
      bookingScore: 8.5,
      reviewCount: 256,
      pricePerNight: 107.06,
      totalPrice: 321.17,
      nights: 3,
      currency: 'EUR',
      address: 'Praia de Moreré S/N',
      lat: -13.609489,
      lng: -38.907113,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-morere.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 58,
      priceVsAnchor: -25.1,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '8139914',
      name: 'Pousada Feliz Boipeba Apartamentos',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 93,
      pricePerNight: 115.11,
      totalPrice: 345.32,
      nights: 3,
      currency: 'EUR',
      address: 'Rua do Porto Boipeba',
      lat: -13.582509,
      lng: -38.92914,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vilage-feliz-boipeba.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 58,
      priceVsAnchor: -19.5,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '12216876',
      name: 'POUSADA e BANGALOS VILA DA BARCA',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 109.62,
      totalPrice: 328.87,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Praia Boca da Barra',
      lat: -13.580628,
      lng: -38.921631,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-e-bangalos-vila-da-barca.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 58,
      priceVsAnchor: -23.3,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '635366',
      name: 'Pousada Fasani',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 111.34,
      totalPrice: 334.01,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Tiririca s/n',
      lat: -13.586783,
      lng: -38.925891,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-fasani.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 58,
      priceVsAnchor: -22.1,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '15983083',
      name: 'Mar de Moreré',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 142.89,
      totalPrice: 428.68,
      nights: 3,
      currency: 'EUR',
      address: 'Moreré Cairu',
      lat: -13.611862,
      lng: -38.90711,
      bookingUrl: 'https://www.booking.com/hotel/br/mar-de-morere.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 58,
      priceVsAnchor: -0.1,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '1685482',
      name: 'Pousada Nascente do Sol',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 170.86,
      totalPrice: 512.58,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Praia Boca da Barra 7',
      lat: -13.578883,
      lng: -38.925985,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-nascente-do-sol-ilha-de-boipeba1.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 58,
      priceVsAnchor: 19.5,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '275564',
      name: 'Pousada Horizonte Azul',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 173.00,
      totalPrice: 519.00,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Travessa da Praia S/N',
      lat: -13.57933,
      lng: -38.926148,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-horizonte-azul.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 58,
      priceVsAnchor: 21.0,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
