/**
 * Données réelles Booking.com — Ilha de Boipeba
 * Recherche MCP effectuée le 14/05/2026
 * Ancre : Pouso da Maré · 143 €/nuit · 0★ · note 9.1
 * Dates : 2026-08-18 → 2026-08-21 (3 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const BOIPEBA_RESULTS: SearchResults = {
  nights: 3,
  searchedAt: '2026-05-14T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pouso da Maré',
    destination: 'Ilha de Boipeba',
    checkinDate: '2026-08-18',
    checkoutDate: '2026-08-21',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-pouso-da-mare.fr.html',
    pricePerNight: 143,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.1,
    services: [],
    vfmScore: 58,
    nights: 3,
    totalPrice: 429,
    lat: -13.580,
    lng: -38.925,
    address: 'Rua da Praia, 58, Île de Boipeba',
    reviewCount: 242,
    facilities: ['breakfast', 'sea_view', 'spa', 'wifi'],
  },

  alternatives: [
    {
      id: '9154138',
      name: 'Pousada Vila Palma Boipeba',
      stars: 4,
      bookingScore: 8.9,
      reviewCount: 275,
      pricePerNight: 110.02,
      totalPrice: 330.06,
      nights: 3,
      currency: 'EUR',
      address: 'Praia Boca da Barra 07, Ilha de Boipeba',
      lat: -13.579573,
      lng: -38.927073,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vila-palma-cairu1.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 58,
      priceVsAnchor: -23.1,
      scoreVsAnchor: -0.2,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '10536926',
      name: 'Pousada Maliale',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 203,
      pricePerNight: 121.70,
      totalPrice: 365.11,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Ilha de São Minguel, frente a praia de boca da barra, Ilha de Boipeba',
      lat: -13.579494,
      lng: -38.934796,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-maliale-boipeba-ilha-de-boipeba-cairu.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'gym', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 58,
      priceVsAnchor: -14.9,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '13460835',
      name: 'Pousada Feliz Boipeba',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 27,
      pricePerNight: 143.54,
      totalPrice: 430.63,
      nights: 3,
      currency: 'EUR',
      address: 'Rua do Porto',
      lat: -13.58221,
      lng: -38.928826,
      bookingUrl: 'https://www.booking.com/hotel/br/villages-feliz-boipeba.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 58,
      priceVsAnchor: 0.4,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '8139914',
      name: 'Pousada Feliz Boipeba Apartamentos',
      stars: 3,
      bookingScore: 8.8,
      reviewCount: 92,
      pricePerNight: 116.84,
      totalPrice: 350.51,
      nights: 3,
      currency: 'EUR',
      address: 'Rua do Porto Boipeba',
      lat: -13.582509,
      lng: -38.92914,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vilage-feliz-boipeba.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 58,
      priceVsAnchor: -18.3,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '12007955',
      name: 'Pousada Coco Dendê',
      stars: 3,
      bookingScore: 8.9,
      reviewCount: 591,
      pricePerNight: 117.53,
      totalPrice: 352.60,
      nights: 3,
      currency: 'EUR',
      address: 'Praça Santo Antônio, Ilha de Boipeba',
      lat: -13.583062,
      lng: -38.927854,
      bookingUrl: 'https://www.booking.com/hotel/br/coco-dende.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 58,
      priceVsAnchor: -17.8,
      scoreVsAnchor: -0.2,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '12216876',
      name: 'POUSADA e BANGALOS VILA DA BARCA',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 111.27,
      totalPrice: 333.82,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Praia Boca da Barra, Ilha de Boipeba',
      lat: -13.580628,
      lng: -38.921631,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-e-bangalos-vila-da-barca.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 58,
      priceVsAnchor: -22.2,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '635366',
      name: 'Pousada Fasani',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 113.01,
      totalPrice: 339.03,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Tiririca, s/n, Ilha de Boipeba',
      lat: -13.586783,
      lng: -38.925891,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-fasani.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 58,
      priceVsAnchor: -21.0,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '15983083',
      name: 'Mar de Moreré',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 130.82,
      totalPrice: 392.47,
      nights: 3,
      currency: 'EUR',
      address: 'Moreré, Cairu',
      lat: -13.611862,
      lng: -38.90711,
      bookingUrl: 'https://www.booking.com/hotel/br/mar-de-morere.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 16,
      anchorVfmScore: 58,
      priceVsAnchor: -8.5,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '275564',
      name: 'Pousada Horizonte Azul',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 175.60,
      totalPrice: 526.81,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Travessa da Praia, S/N, Ilha de Boipeba',
      lat: -13.57933,
      lng: -38.926148,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-horizonte-azul.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 58,
      priceVsAnchor: 22.8,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1685482',
      name: 'Pousada Nascente do Sol',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 173.43,
      totalPrice: 520.29,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Praia Boca da Barra, 7, Ilha de Boipeba',
      lat: -13.578883,
      lng: -38.925985,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-nascente-do-sol-ilha-de-boipeba1.html?aid=8132308&checkin=2026-08-18&checkout=2026-08-21&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 58,
      priceVsAnchor: 21.3,
      scoreVsAnchor: -9.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
