/**
 * Données réelles Booking.com — Fortaleza
 * Recherche MCP effectuée le 13/05/2026
 * Ancre : Praiano Hotel · 164 €/nuit · 0★ · note 9.0
 * Dates : 16/08/2026 → 17/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const FORTALEZA_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-13T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Praiano Hotel',
    destination: 'Fortaleza',
    checkinDate: '2026-08-16',
    checkoutDate: '2026-08-17',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/praiano-fortaleza.fr.html',
    pricePerNight: 164,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.0,
    services: [],
    vfmScore: 58,
    nights: 1,
    totalPrice: 164,
    lat: -3.724,
    lng: -38.503,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '1558272',
      name: 'Gran Mareiro Hotel',
      stars: 5,
      bookingScore: 9.0,
      reviewCount: 2347,
      pricePerNight: 138.49,
      totalPrice: 138.49,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Osvaldo Araújo, 100, Praia do Futuro I, Fortaleza',
      lat: -3.739429,
      lng: -38.453422,
      bookingUrl: 'https://www.booking.com/hotel/br/gran-mareiro.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 69,
      anchorVfmScore: 58,
      priceVsAnchor: -15.6,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 5,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '3082389',
      name: 'Pauli Boutique Hotel',
      stars: 4,
      bookingScore: 8.9,
      reviewCount: 2306,
      pricePerNight: 171.88,
      totalPrice: 171.88,
      nights: 1,
      currency: 'EUR',
      address: '3806 Avenida da Abolição, Mucuripe, Fortaleza',
      lat: -3.725862,
      lng: -38.485478,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-mucuripe.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: 4.8,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '6072816',
      name: 'Beach Class Exclusive',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 494,
      pricePerNight: 130.12,
      totalPrice: 130.12,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Barão de Aracati 145, Meireles, Fortaleza',
      lat: -3.723226,
      lng: -38.508478,
      bookingUrl: 'https://www.booking.com/hotel/br/beach-class-exclusive.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: -20.7,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '12160',
      name: 'Hotel Praia Centro',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 1134,
      pricePerNight: 166.30,
      totalPrice: 166.30,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Monsenhor Tabosa, 740, Meireles, Fortaleza',
      lat: -3.724382,
      lng: -38.512273,
      bookingUrl: 'https://www.booking.com/hotel/br/praia-centro.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: 1.4,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '12271',
      name: 'Hotel Beira Mar',
      stars: 4,
      bookingScore: 8.5,
      reviewCount: 1583,
      pricePerNight: 159.83,
      totalPrice: 159.83,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Beira Mar, 3130, Meireles, Fortaleza',
      lat: -3.725781,
      lng: -38.492175,
      bookingUrl: 'https://www.booking.com/hotel/br/beira-mar.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 58,
      priceVsAnchor: -2.5,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '12229',
      name: 'Hotel Brasil Tropical',
      stars: 4,
      bookingScore: 8.6,
      reviewCount: 2158,
      pricePerNight: 166.66,
      totalPrice: 166.66,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Abolição, 2323, Meireles, Fortaleza',
      lat: -3.726218,
      lng: -38.497869,
      bookingUrl: 'https://www.booking.com/hotel/br/brasil-tropical-residence.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 58,
      priceVsAnchor: 1.6,
      scoreVsAnchor: -0.4,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '8983577',
      name: 'Tintto Hotel',
      stars: 4,
      bookingScore: 8.4,
      reviewCount: 1271,
      pricePerNight: 171.29,
      totalPrice: 171.29,
      nights: 1,
      currency: 'EUR',
      address: '727 Avenida Almirante Barroso, Praia de Iracema, Fortaleza',
      lat: -3.720249,
      lng: -38.516481,
      bookingUrl: 'https://www.booking.com/hotel/br/tintto.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 58,
      priceVsAnchor: 4.4,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '12717',
      name: 'Afago Mareiro Hotel',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 1732,
      pricePerNight: 192.63,
      totalPrice: 192.63,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Beira Mar, 2380, Meireles, Fortaleza',
      lat: -3.725356,
      lng: -38.499261,
      bookingUrl: 'https://www.booking.com/hotel/br/olympo-praia.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 58,
      priceVsAnchor: 17.5,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '12222',
      name: 'Hotel Villa Mayor Charme',
      stars: 4,
      bookingScore: 8.1,
      reviewCount: 1283,
      pricePerNight: 172.85,
      totalPrice: 172.85,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Visconde de Mauá, 151, Meireles, Fortaleza',
      lat: -3.727611,
      lng: -38.496576,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-mayor.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 58,
      priceVsAnchor: 5.4,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1073431',
      name: 'Pousada Fortal Villa Praia',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 123.74,
      totalPrice: 123.74,
      nights: 1,
      currency: 'EUR',
      address: 'Rua dos Ararius, 2, Praia de Iracema, Fortaleza',
      lat: -3.71967,
      lng: -38.513401,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-iracema-villa-praia.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 58,
      priceVsAnchor: -24.5,
      scoreVsAnchor: -9.0,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
  ],
};
