/**
 * Données réelles Booking.com — Fortaleza
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Praiano Hotel · 164 €/nuit · 4★ · note 9.0
 * Dates : 2026-08-16 → 2026-08-17 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const FORTALEZA_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Praiano Hotel',
    destination: 'Fortaleza',
    checkinDate: '2026-08-16',
    checkoutDate: '2026-08-17',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/praiano-fortaleza.fr.html',
    pricePerNight: 164,
    currency: 'EUR',
    stars: 4,
    bookingScore: 9.0,
    services: [],
    vfmScore: 74,
    nights: 1,
    totalPrice: 164,
    lat: -3.724,
    lng: -38.503,
    address: 'Av. Beira Mar, 2800, Meireles, Fortaleza',
    reviewCount: 3319,
    facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
  },

  alternatives: [
    {
      id: '8118995',
      name: 'Stop Way Hotel Fortaleza',
      stars: 3,
      bookingScore: 8.9,
      reviewCount: 2535,
      pricePerNight: 121.16,
      totalPrice: 121.16,
      nights: 1,
      currency: 'EUR',
      address: 'AV MONSENHOR TABOSA 940',
      lat: -3.724382,
      lng: -38.511173,
      bookingUrl: 'https://www.booking.com/hotel/br/stop-way-fortaleza.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 74,
      priceVsAnchor: -26.1,
      scoreVsAnchor: -0.1,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '19169',
      name: 'Bristol Jangada Fortaleza Meirelles',
      stars: 4,
      bookingScore: 8.5,
      reviewCount: 1595,
      pricePerNight: 135.41,
      totalPrice: 135.41,
      nights: 1,
      currency: 'EUR',
      address: 'Av da Abolição 3035',
      lat: -3.726736,
      lng: -38.492158,
      bookingUrl: 'https://www.booking.com/hotel/br/bristol-jangada-fortaleza-meirelles.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 74,
      priceVsAnchor: -17.4,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '6072816',
      name: 'Beach Class Exclusive',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 494,
      pricePerNight: 121.27,
      totalPrice: 121.27,
      nights: 1,
      currency: 'EUR',
      address: 'rua barao de aracati 145',
      lat: -3.723226,
      lng: -38.508478,
      bookingUrl: 'https://www.booking.com/hotel/br/beach-class-exclusive.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 74,
      priceVsAnchor: -26.1,
      scoreVsAnchor: -0.6,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '6300047',
      name: 'Grupo Vip Beach Class Fortaleza',
      stars: 4,
      bookingScore: 8.0,
      reviewCount: 63,
      pricePerNight: 126.33,
      totalPrice: 126.33,
      nights: 1,
      currency: 'EUR',
      address: 'rua barao de aracati 145',
      lat: -3.723226,
      lng: -38.508478,
      bookingUrl: 'https://www.booking.com/hotel/br/grupo-vip-beach-class-fortaleza.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'gym', 'parking', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 74,
      priceVsAnchor: -23.0,
      scoreVsAnchor: -1.0,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '2819365',
      name: 'Hotel Villa Smart',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 542,
      pricePerNight: 120.19,
      totalPrice: 120.19,
      nights: 1,
      currency: 'EUR',
      address: '185 Rua Visconde de Mauá',
      lat: -3.727817,
      lng: -38.496673,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-smart.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 74,
      priceVsAnchor: -26.7,
      scoreVsAnchor: -0.8,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '12160',
      name: 'Hotel Praia Centro',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 1137,
      pricePerNight: 157.12,
      totalPrice: 157.12,
      nights: 1,
      currency: 'EUR',
      address: 'Av Monsenhor Tabosa 740',
      lat: -3.724382,
      lng: -38.512273,
      bookingUrl: 'https://www.booking.com/hotel/br/praia-centro.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 74,
      priceVsAnchor: -4.2,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '12271',
      name: 'Hotel Beira Mar',
      stars: 4,
      bookingScore: 8.5,
      reviewCount: 1564,
      pricePerNight: 157.59,
      totalPrice: 157.59,
      nights: 1,
      currency: 'EUR',
      address: 'Av Beira Mar 3130',
      lat: -3.725781,
      lng: -38.492175,
      bookingUrl: 'https://www.booking.com/hotel/br/beira-mar.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 74,
      priceVsAnchor: -3.9,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '12229',
      name: 'Hotel Brasil Tropical',
      stars: 4,
      bookingScore: 8.6,
      reviewCount: 2135,
      pricePerNight: 164.32,
      totalPrice: 164.32,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Abolição 2323',
      lat: -3.726218,
      lng: -38.497869,
      bookingUrl: 'https://www.booking.com/hotel/br/brasil-tropical.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 74,
      priceVsAnchor: 0.2,
      scoreVsAnchor: -0.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '12717',
      name: 'Afago Mareiro Hotel',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 1732,
      pricePerNight: 189.92,
      totalPrice: 189.92,
      nights: 1,
      currency: 'EUR',
      address: 'Av Beira Mar 2380',
      lat: -3.725356,
      lng: -38.499261,
      bookingUrl: 'https://www.booking.com/hotel/br/afago-mareiro.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 74,
      priceVsAnchor: 15.8,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '12222',
      name: 'Hotel Villa Mayor Charme',
      stars: 4,
      bookingScore: 8.1,
      reviewCount: 1279,
      pricePerNight: 178.92,
      totalPrice: 178.92,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Visconde de Mauá 151',
      lat: -3.727611,
      lng: -38.496576,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-mayor.html?aid=8132308&checkin=2026-08-16&checkout=2026-08-17&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 74,
      priceVsAnchor: 9.1,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
