/**
 * Données réelles Booking.com — Jericoacoara
 * Recherche MCP effectuée le 14/05/2026
 * Ancre : Mym Dunas · 120 €/nuit · 0★ · note 9.3
 * Dates : 2026-08-12 → 2026-08-16 (4 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const JERICOACOARA_RESULTS: SearchResults = {
  nights: 4,
  searchedAt: '2026-05-14T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Mym Dunas',
    destination: 'Jericoacoara',
    checkinDate: '2026-08-12',
    checkoutDate: '2026-08-16',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-la-luna-jericoacoara.fr.html',
    pricePerNight: 120,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.3,
    services: [],
    vfmScore: 59,
    nights: 4,
    totalPrice: 480,
    lat: -2.796,
    lng: -40.514,
    address: 'Rua Das Dunas, Nº 4, Jericoacoara',
    reviewCount: 392,
    facilities: ['breakfast', 'pool', 'wifi'],
  },

  alternatives: [
    {
      id: '2314715',
      name: 'Swiss Garten Jeri',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 89,
      pricePerNight: 133.11,
      totalPrice: 532.44,
      nights: 4,
      currency: 'EUR',
      address: 'Rua da Igreja 205',
      lat: -2.793856,
      lng: -40.518318,
      bookingUrl: 'https://www.booking.com/hotel/br/swiss-garten-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 59,
      priceVsAnchor: 10.9,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '242425',
      name: 'Eco Resort Vento Leste',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 115,
      pricePerNight: 115.27,
      totalPrice: 461.09,
      nights: 4,
      currency: 'EUR',
      address: 'R. Nova Jeri S/n',
      lat: -2.799503,
      lng: -40.510143,
      bookingUrl: 'https://www.booking.com/hotel/br/eco-resorte-vento-leste.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 59,
      priceVsAnchor: -3.9,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '4617381',
      name: 'Casarão Jeri',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 145,
      pricePerNight: 118.23,
      totalPrice: 472.91,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró',
      lat: -2.79452,
      lng: -40.517782,
      bookingUrl: 'https://www.booking.com/hotel/br/casarao-jeri-jijoca-de-jericoacoara.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 59,
      priceVsAnchor: -1.5,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '12456902',
      name: 'Pousada Isabel Araújo',
      stars: 4,
      bookingScore: 8.0,
      reviewCount: 364,
      pricePerNight: 110.06,
      totalPrice: 440.22,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró',
      lat: -2.794546,
      lng: -40.519482,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-isabel-araujo-vila-de-jericoacoara.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 59,
      priceVsAnchor: -8.3,
      scoreVsAnchor: -1.3,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '8861365',
      name: 'Pousada Hippopotamus Jeri',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 638,
      pricePerNight: 134.93,
      totalPrice: 539.71,
      nights: 4,
      currency: 'EUR',
      address: '51 Rua da Igreja',
      lat: -2.793732,
      lng: -40.517449,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-hippopotamus-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 59,
      priceVsAnchor: 12.4,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '868254',
      name: 'Villa Chic Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 98.96,
      totalPrice: 395.83,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Principal s/n',
      lat: -2.795551,
      lng: -40.513985,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-chic-hostel-pousada.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 59,
      priceVsAnchor: -17.5,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '336893',
      name: 'Pousada Por do Sol',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 109.05,
      totalPrice: 436.19,
      nights: 4,
      currency: 'EUR',
      address: 'Rua das Dunas, 50',
      lat: -2.797789,
      lng: -40.515553,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-por-do-sol-jericoacoara.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 59,
      priceVsAnchor: -9.1,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '4110553',
      name: 'Pousada Sunbrazil',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 124.26,
      totalPrice: 497.04,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró s/n',
      lat: -2.794303,
      lng: -40.516851,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-sunbrazil.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 59,
      priceVsAnchor: 3.6,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '6750900',
      name: 'Pousada Coral Negro',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 141.27,
      totalPrice: 565.06,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Ricardo Martins S/N, Vila de Jericoacoara',
      lat: -2.79509,
      lng: -40.517501,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vila-rufino.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 59,
      priceVsAnchor: 17.7,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '9420829',
      name: 'Beco do Mar Jeri',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 140.52,
      totalPrice: 562.07,
      nights: 4,
      currency: 'EUR',
      address: 'Rua da Igreja',
      lat: -2.79394,
      lng: -40.516768,
      bookingUrl: 'https://www.booking.com/hotel/br/ronco-do-mar-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 59,
      priceVsAnchor: 17.1,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
  ],
};
