/**
 * Données réelles Booking.com — Jericoacoara
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Mym Dunas · 120 €/nuit · 0★ · note 9.3
 * Dates : 2026-08-12 → 2026-08-16 (4 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const JERICOACOARA_RESULTS: SearchResults = {
  nights: 4,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Mym Dunas',
    destination: 'Jericoacoara',
    checkinDate: '2026-08-12',
    checkoutDate: '2026-08-16',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-la-luna-jericoacoara.fr.html',
    pricePerNight: 120,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.3,
    services: [],
    vfmScore: 59,
    nights: 4,
    totalPrice: 480,
    lat: -2.796,
    lng: -40.514,
    address: 'Rua Das Dunas, Nº 4, Jericoacoara',
    reviewCount: 392,
    facilities: ['breakfast', 'pool', 'wifi'],
  },

  alternatives: [
    {
      id: '4445203',
      name: 'Villa das Palmeiras Jeri',
      stars: 3,
      bookingScore: 9.4,
      reviewCount: 523,
      pricePerNight: 82.75,
      totalPrice: 331.00,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Vital Veríssimo S/N',
      lat: -2.798321,
      lng: -40.510563,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-das-palmeiras-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 59,
      priceVsAnchor: -31.0,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '2314715',
      name: 'Swiss Garten Jeri',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 88,
      pricePerNight: 131.22,
      totalPrice: 524.88,
      nights: 4,
      currency: 'EUR',
      address: 'Rua da Igreja 205',
      lat: -2.793856,
      lng: -40.518318,
      bookingUrl: 'https://www.booking.com/hotel/br/swiss-garten-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 59,
      priceVsAnchor: 9.4,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '242425',
      name: 'Eco Resort Vento Leste',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 115,
      pricePerNight: 113.64,
      totalPrice: 454.54,
      nights: 4,
      currency: 'EUR',
      address: 'R. Nova Jeri S/n',
      lat: -2.799503,
      lng: -40.510143,
      bookingUrl: 'https://www.booking.com/hotel/br/eco-resorte-vento-leste.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 59,
      priceVsAnchor: -5.3,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '12456902',
      name: 'Pousada Isabel Araújo',
      stars: 4,
      bookingScore: 7.9,
      reviewCount: 369,
      pricePerNight: 92.22,
      totalPrice: 368.87,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró',
      lat: -2.794546,
      lng: -40.519482,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-isabel-araujo-vila-de-jericoacoara.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 59,
      priceVsAnchor: -23.2,
      scoreVsAnchor: -1.4,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '8861365',
      name: 'Pousada Hippopotamus Jeri',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 640,
      pricePerNight: 133.01,
      totalPrice: 532.04,
      nights: 4,
      currency: 'EUR',
      address: '51 Rua da Igreja',
      lat: -2.793732,
      lng: -40.517449,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-hippopotamus-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 59,
      priceVsAnchor: 10.8,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '3609891',
      name: 'Rede Andrade Dunas',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 214,
      pricePerNight: 99.65,
      totalPrice: 398.59,
      nights: 4,
      currency: 'EUR',
      address: 'Rua da Usina Nº 18',
      lat: -2.800877,
      lng: -40.512068,
      bookingUrl: 'https://www.booking.com/hotel/br/rede-andrade-dunas.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 59,
      priceVsAnchor: -17.0,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '6708092',
      name: 'Pousada Maxitalia',
      stars: 4,
      bookingScore: 9.0,
      reviewCount: 378,
      pricePerNight: 155.35,
      totalPrice: 621.38,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Genesio Melo 108, Centro Jericoacoara',
      lat: -2.795715,
      lng: -40.514104,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-maxitalia.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 59,
      priceVsAnchor: 29.5,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '868254',
      name: 'Villa Chic Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 97.55,
      totalPrice: 390.20,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Principal s/n',
      lat: -2.795551,
      lng: -40.513985,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-chic-hostel-pousada.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 59,
      priceVsAnchor: -18.7,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '4110553',
      name: 'Pousada Sunbrazil',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 117.58,
      totalPrice: 470.31,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró s/n',
      lat: -2.794303,
      lng: -40.516851,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-sunbrazil.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 59,
      priceVsAnchor: -2.0,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '6750900',
      name: 'Pousada Coral Negro',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 152.11,
      totalPrice: 608.45,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Ricardo Martins S/N',
      lat: -2.79509,
      lng: -40.517501,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-vila-rufino.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 59,
      priceVsAnchor: 26.8,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
  ],
};
