/**
 * Données réelles Booking.com — Jericoacoara
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Mym Dunas · 120 €/nuit · 0★ · note 9.3
 * Dates : 2026-08-12 → 2026-08-16 (4 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const JERICOACOARA_RESULTS: SearchResults = {
  nights: 4,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Mym Dunas',
    destination: 'Jericoacoara',
    checkinDate: '2026-08-12',
    checkoutDate: '2026-08-16',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-la-luna-jericoacoara.fr.html',
    pricePerNight: 120,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.3,
    services: [],
    vfmScore: 59,
    nights: 4,
    totalPrice: 480,
    lat: -2.796,
    lng: -40.514,
    address: 'Rua Das Dunas, Nº 4, Jericoacoara',
    reviewCount: 392,
    facilities: ['breakfast', 'pool', 'wifi'],
  },

  alternatives: [
    {
      id: '12456902',
      name: 'Pousada Isabel Araújo',
      stars: 4,
      bookingScore: 7.9,
      reviewCount: 372,
      pricePerNight: 92.16,
      totalPrice: 368.65,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró',
      lat: -2.794546,
      lng: -40.519482,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-isabel-araujo-vila-de-jericoacoara.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 59,
      priceVsAnchor: -23.2,
      scoreVsAnchor: -1.4,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '242425',
      name: 'Eco Resort Vento Leste',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 114,
      pricePerNight: 113.57,
      totalPrice: 454.26,
      nights: 4,
      currency: 'EUR',
      address: 'R. Nova Jeri S/n',
      lat: -2.799503,
      lng: -40.510143,
      bookingUrl: 'https://www.booking.com/hotel/br/eco-resorte-vento-leste.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 59,
      priceVsAnchor: -5.4,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '14106726',
      name: 'Casa Manari',
      stars: 3,
      bookingScore: 9.6,
      reviewCount: 59,
      pricePerNight: 119.90,
      totalPrice: 479.61,
      nights: 4,
      currency: 'EUR',
      address: 'Beco da Padaria',
      lat: -2.79518,
      lng: -40.516035,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-manari.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 59,
      priceVsAnchor: -0.1,
      scoreVsAnchor: 0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '3609891',
      name: 'Rede Andrade Dunas',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 227,
      pricePerNight: 99.59,
      totalPrice: 398.35,
      nights: 4,
      currency: 'EUR',
      address: 'Rua da Usina 18',
      lat: -2.800877,
      lng: -40.512068,
      bookingUrl: 'https://www.booking.com/hotel/br/rede-andrade-dunas.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 59,
      priceVsAnchor: -17.0,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '8861365',
      name: 'Pousada Hippopotamus Jeri',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 640,
      pricePerNight: 132.93,
      totalPrice: 531.71,
      nights: 4,
      currency: 'EUR',
      address: '51 Rua da Igreja',
      lat: -2.793732,
      lng: -40.517449,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-hippopotamus-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 59,
      priceVsAnchor: 10.8,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '2554878',
      name: 'Residence Bons Ventos Jeri',
      stars: 3,
      bookingScore: 8.9,
      reviewCount: 1316,
      pricePerNight: 147.31,
      totalPrice: 589.23,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró',
      lat: -2.794724,
      lng: -40.515647,
      bookingUrl: 'https://www.booking.com/hotel/br/residence-bons-ventos-jeri.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 57,
      anchorVfmScore: 59,
      priceVsAnchor: 22.8,
      scoreVsAnchor: -0.4,
      starsVsAnchor: 3,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '354949',
      name: 'Pousada da Renata',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 107.91,
      totalPrice: 431.65,
      nights: 4,
      currency: 'EUR',
      address: 'Rua da Escola, s/n',
      lat: -2.796224,
      lng: -40.511416,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-da-renata.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 59,
      priceVsAnchor: -10.1,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '4110553',
      name: 'Pousada Sunbrazil',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 117.50,
      totalPrice: 470.01,
      nights: 4,
      currency: 'EUR',
      address: 'Rua do Forró s/n',
      lat: -2.794303,
      lng: -40.516851,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-sunbrazil.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 59,
      priceVsAnchor: -2.1,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '868254',
      name: 'Villa Chic Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 137.10,
      totalPrice: 548.39,
      nights: 4,
      currency: 'EUR',
      address: 'Rua Principal s/n',
      lat: -2.795551,
      lng: -40.513985,
      bookingUrl: 'https://www.booking.com/hotel/br/villa-chic-hostel-pousada.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 59,
      priceVsAnchor: 14.3,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '341930',
      name: 'Pousada Atlantis',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 140.73,
      totalPrice: 562.92,
      nights: 4,
      currency: 'EUR',
      address: 'Rua das Dunas, s/n',
      lat: -2.797829,
      lng: -40.515916,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-atlantis-jericoacoara.html?aid=8132308&checkin=2026-08-12&checkout=2026-08-16&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 59,
      priceVsAnchor: 17.3,
      scoreVsAnchor: -9.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
  ],
};
