/**
 * Données réelles Booking.com — Parnaíba
 * Recherche MCP effectuée le 14/05/2026
 * Ancre : Oceane Norte Hotel · 89 €/nuit · 0★ · note 8.8
 * Dates : 2026-08-11 → 2026-08-12 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const PARNABA_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-14T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Oceane Norte Hotel',
    destination: 'Parnaíba',
    checkinDate: '2026-08-11',
    checkoutDate: '2026-08-12',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/oceane-norte.fr.html',
    pricePerNight: 89,
    currency: 'EUR',
    stars: 0,
    bookingScore: 8.8,
    services: [],
    vfmScore: 57,
    nights: 1,
    totalPrice: 89,
    lat: -2.908,
    lng: -41.749,
    address: 'Rua Senador Getulio Vargas 41, Parnaíba',
    reviewCount: 0,
    facilities: ['ac', 'wifi'],
  },

  alternatives: [
    {
      id: '13493896',
      name: 'Aconchego Dourado',
      stars: 4,
      bookingScore: 9.8,
      reviewCount: 33,
      pricePerNight: 83.45,
      totalPrice: 83.45,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Santo Agostinho 725',
      lat: -2.921602,
      lng: -41.727524,
      bookingUrl: 'https://www.booking.com/hotel/br/alugue-casa-com-piscina-a-15min-da-praia.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 57,
      priceVsAnchor: -6.2,
      scoreVsAnchor: 1.0,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '13731157',
      name: 'Delta Prime HOTEL',
      stars: 3,
      bookingScore: 8.0,
      reviewCount: 179,
      pricePerNight: 90.41,
      totalPrice: 90.41,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Presidente Getúlio Vargas, 268 SALA 002',
      lat: -2.901942,
      lng: -41.779427,
      bookingUrl: 'https://www.booking.com/hotel/br/delta-prime-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 57,
      priceVsAnchor: 1.6,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '2861961',
      name: 'Pousada Lunar',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 67.89,
      totalPrice: 67.89,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Rodrigues Coimbra, 1810',
      lat: -2.926851,
      lng: -41.747768,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-lunar.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 57,
      priceVsAnchor: -23.7,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '7979995',
      name: 'SOLAR HOSTEL PARNAIBA',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 69.20,
      totalPrice: 69.20,
      nights: 1,
      currency: 'EUR',
      address: 'RUA FLORINDO DE CASTRO, 475 - SALA 05',
      lat: -2.907301,
      lng: -41.774388,
      bookingUrl: 'https://www.booking.com/hotel/br/solar-hostel-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 57,
      priceVsAnchor: -22.2,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '10411987',
      name: 'Pousada Aeroporto',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 72.33,
      totalPrice: 72.33,
      nights: 1,
      currency: 'EUR',
      address: '4289 BR-343',
      lat: -2.900888,
      lng: -41.735338,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-aeroporto-parnaiba1.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 57,
      priceVsAnchor: -18.7,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '3539150',
      name: 'Pousada Vila Cajuína',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 85.02,
      totalPrice: 85.02,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Coronel Carlos Alberto Prado da Cunha, 830, Reis Veloso',
      lat: -2.904215,
      lng: -41.73371,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-cajuina.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 16,
      anchorVfmScore: 57,
      priceVsAnchor: -4.5,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13957785',
      name: 'Bru&Mar Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 86.41,
      totalPrice: 86.41,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Ramiro Santos 260',
      lat: -2.90575,
      lng: -41.751409,
      bookingUrl: 'https://www.booking.com/hotel/br/bru-amp-mar-pousada.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 57,
      priceVsAnchor: -2.9,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '5627082',
      name: 'Hotel Cajuína Beach',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 90.41,
      totalPrice: 90.41,
      nights: 1,
      currency: 'EUR',
      address: 'RUA MIGUEL NASCIMENTO N 260 BAIRRO FLORIOPOLIS N 260- B - URBANO',
      lat: -2.900402,
      lng: -41.715277,
      bookingUrl: 'https://www.booking.com/hotel/br/cajuina-beach.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 57,
      priceVsAnchor: 1.6,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '12994395',
      name: 'Casa litoral',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 102.23,
      totalPrice: 102.23,
      nights: 1,
      currency: 'EUR',
      address: '11 Rua Otávio Passos',
      lat: -2.907281,
      lng: -41.752814,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-litoral-parnaiba1.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 57,
      priceVsAnchor: 14.9,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '280914',
      name: 'Hotel Pousada Dos Ventos',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 107.87,
      totalPrice: 107.87,
      nights: 1,
      currency: 'EUR',
      address: 'Av. São Sebastião, 2586',
      lat: -2.91024,
      lng: -41.74726,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-dos-ventos-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 57,
      priceVsAnchor: 21.2,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
  ],
};
