/**
 * Données réelles Booking.com — Parnaíba
 * Recherche MCP effectuée le 13/05/2026
 * Ancre : Oceane Norte Hotel · 89 €/nuit · 0★ · note 8.8
 * Dates : 11/08/2026 → 12/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const PARNABA_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-13T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Oceane Norte Hotel',
    destination: 'Parnaíba',
    checkinDate: '2026-08-11',
    checkoutDate: '2026-08-12',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/oceane-norte.fr.html',
    pricePerNight: 89,
    currency: 'EUR',
    stars: 0,
    bookingScore: 8.8,
    services: [],
    vfmScore: 57,
    nights: 1,
    totalPrice: 89,
    lat: -2.901,
    lng: -41.779,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '13493896',
      name: 'Aconchego Dourado',
      stars: 4,
      bookingScore: 9.8,
      reviewCount: 33,
      pricePerNight: 83.39,
      totalPrice: 83.39,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Santo Agostinho 725, Parnaíba',
      lat: -2.921602,
      lng: -41.727524,
      bookingUrl: 'https://www.booking.com/hotel/br/alugue-casa-com-piscina-a-15min-da-praia.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 57,
      priceVsAnchor: -6.3,
      scoreVsAnchor: 1.0,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '13731157',
      name: 'Delta Prime Hotel',
      stars: 3,
      bookingScore: 8.0,
      reviewCount: 179,
      pricePerNight: 90.34,
      totalPrice: 90.34,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Presidente Getúlio Vargas, 268, Parnaíba',
      lat: -2.901942,
      lng: -41.779427,
      bookingUrl: 'https://www.booking.com/hotel/br/delta-prime-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 57,
      priceVsAnchor: 1.5,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '2861961',
      name: 'Pousada Lunar',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 67.83,
      totalPrice: 67.83,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Rodrigues Coimbra, 1810, Parnaíba',
      lat: -2.926851,
      lng: -41.747768,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-lunar.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 57,
      priceVsAnchor: -23.8,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '10411987',
      name: 'Pousada Aeroporto',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 72.27,
      totalPrice: 72.27,
      nights: 1,
      currency: 'EUR',
      address: '4289 BR-343, Parnaíba',
      lat: -2.900888,
      lng: -41.735338,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-aeroporto-parnaiba1.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 18,
      anchorVfmScore: 57,
      priceVsAnchor: -18.8,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '3539150',
      name: 'Pousada Vila Cajuína',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 84.95,
      totalPrice: 84.95,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Coronel Carlos Alberto Prado da Cunha, 830, Reis Veloso, Parnaíba',
      lat: -2.904215,
      lng: -41.73371,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-cajuina.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 16,
      anchorVfmScore: 57,
      priceVsAnchor: -4.5,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '5627082',
      name: 'Hotel Cajuína Beach',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 90.34,
      totalPrice: 90.34,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Miguel Nascimento N 260, Bairro Floriopolis, Parnaíba',
      lat: -2.900402,
      lng: -41.715277,
      bookingUrl: 'https://www.booking.com/hotel/br/cajuina-beach.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 57,
      priceVsAnchor: 1.5,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13957785',
      name: 'Bru&Mar Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 86.34,
      totalPrice: 86.34,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Ramiro Santos 260, Parnaíba',
      lat: -2.90575,
      lng: -41.751409,
      bookingUrl: 'https://www.booking.com/hotel/br/bru-amp-mar-pousada.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 57,
      priceVsAnchor: -3.0,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '12994395',
      name: 'Casa litoral',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 102.15,
      totalPrice: 102.15,
      nights: 1,
      currency: 'EUR',
      address: '11 Rua Otávio Passos, Parnaíba',
      lat: -2.907281,
      lng: -41.752814,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-litoral-parnaiba1.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 57,
      priceVsAnchor: 14.8,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '280914',
      name: 'Hotel Pousada Dos Ventos',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 107.78,
      totalPrice: 107.78,
      nights: 1,
      currency: 'EUR',
      address: 'Av. São Sebastião, 2586, Parnaíba',
      lat: -2.91024,
      lng: -41.74726,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-dos-ventos-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 57,
      priceVsAnchor: 21.1,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
  ],
};
