/**
 * Données réelles Booking.com — Parnaíba
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Oceane Norte Hotel · 89 €/nuit · 0★ · note 8.8
 * Dates : 2026-08-11 → 2026-08-12 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const PARNABA_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Oceane Norte Hotel',
    destination: 'Parnaíba',
    checkinDate: '2026-08-11',
    checkoutDate: '2026-08-12',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/oceane-norte.fr.html',
    pricePerNight: 89,
    currency: 'EUR',
    stars: 0,
    bookingScore: 8.8,
    services: [],
    vfmScore: 57,
    nights: 1,
    totalPrice: 89,
    lat: -2.908,
    lng: -41.749,
    address: 'Rua Senador Getulio Vargas 41, Parnaíba',
    reviewCount: 0,
    facilities: ['ac', 'wifi'],
  },

  alternatives: [
    {
      id: '15796151',
      name: 'Meu Lugar Parnaiba',
      stars: 3,
      bookingScore: 9.5,
      reviewCount: 33,
      pricePerNight: 63.38,
      totalPrice: 63.38,
      nights: 1,
      currency: 'EUR',
      address: '475 Rua Belarmino Pires',
      lat: -2.906427,
      lng: -41.745823,
      bookingUrl: 'https://www.booking.com/hotel/br/meu-lugar-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 57,
      priceVsAnchor: -28.8,
      scoreVsAnchor: 0.7,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '13493896',
      name: 'Aconchego Dourado',
      stars: 4,
      bookingScore: 9.8,
      reviewCount: 35,
      pricePerNight: 82.22,
      totalPrice: 82.22,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Santo Agostinho 725',
      lat: -2.921602,
      lng: -41.727524,
      bookingUrl: 'https://www.booking.com/hotel/br/alugue-casa-com-piscina-a-15min-da-praia.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 57,
      priceVsAnchor: -7.6,
      scoreVsAnchor: 1.0,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '13731157',
      name: 'Delta Prime HOTEL',
      stars: 3,
      bookingScore: 8.0,
      reviewCount: 184,
      pricePerNight: 89.07,
      totalPrice: 89.07,
      nights: 1,
      currency: 'EUR',
      address: 'Av Presidente Getúlio Vargas 268',
      lat: -2.901942,
      lng: -41.779427,
      bookingUrl: 'https://www.booking.com/hotel/br/delta-prime-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 57,
      priceVsAnchor: 0.1,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '7979995',
      name: 'SOLAR HOSTEL PARNAIBA',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 56.53,
      totalPrice: 56.53,
      nights: 1,
      currency: 'EUR',
      address: 'RUA FLORINDO DE CASTRO 475',
      lat: -2.907301,
      lng: -41.774388,
      bookingUrl: 'https://www.booking.com/hotel/br/solar-hostel-parnaiba.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 24,
      anchorVfmScore: 57,
      priceVsAnchor: -36.5,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '2861961',
      name: 'Pousada Lunar',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 66.88,
      totalPrice: 66.88,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Rodrigues Coimbra 1810',
      lat: -2.926851,
      lng: -41.747768,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-lunar.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 57,
      priceVsAnchor: -24.9,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '10411987',
      name: 'Pousada Aeroporto',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 71.26,
      totalPrice: 71.26,
      nights: 1,
      currency: 'EUR',
      address: '4289 BR-343',
      lat: -2.900888,
      lng: -41.735338,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-aeroporto-parnaiba1.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 57,
      priceVsAnchor: -19.9,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '405662',
      name: 'Pousada Porto das Barcas',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 78.28,
      totalPrice: 78.28,
      nights: 1,
      currency: 'EUR',
      address: 'Rua do Comercio, 100',
      lat: -2.900181,
      lng: -41.781195,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-porto-das-barcas.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 57,
      priceVsAnchor: -12.0,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13957785',
      name: 'Bru&Mar Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 85.13,
      totalPrice: 85.13,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Ramiro Santos 260',
      lat: -2.90575,
      lng: -41.751409,
      bookingUrl: 'https://www.booking.com/hotel/br/bru-amp-mar-pousada.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 16,
      anchorVfmScore: 57,
      priceVsAnchor: -4.3,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '3539150',
      name: 'Pousada Vila Cajuína',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 105.80,
      totalPrice: 105.80,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Cel Carlos Alberto Prado da Cunha 830',
      lat: -2.904215,
      lng: -41.73371,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-cajuina.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 57,
      priceVsAnchor: 18.9,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '5627082',
      name: 'Hotel Cajuína Beach',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 89.07,
      totalPrice: 89.07,
      nights: 1,
      currency: 'EUR',
      address: 'RUA MIGUEL NASCIMENTO 260',
      lat: -2.900402,
      lng: -41.715277,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel-cajuina-beach.html?aid=8132308&checkin=2026-08-11&checkout=2026-08-12&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 57,
      priceVsAnchor: 0.1,
      scoreVsAnchor: -8.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
  ],
};
