/**
 * Données réelles Booking.com — Rio de Janeiro
 * Recherche MCP effectuée le 16/05/2026
 * Ancre : Atlantis Copacabana Hotel · 175 €/nuit · 3★ · note 8.6
 * Dates : 2026-07-26 → 2026-07-31 (5 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const RIO_RESULTS: SearchResults = {
  nights: 5,
  searchedAt: '2026-05-16T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Atlantis Copacabana Hotel',
    destination: 'Rio de Janeiro',
    checkinDate: '2026-07-26',
    checkoutDate: '2026-07-31',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/atlantis-copacabana.fr.html',
    pricePerNight: 175,
    currency: 'EUR',
    stars: 3,
    bookingScore: 8.6,
    services: [],
    vfmScore: 68,
    nights: 5,
    totalPrice: 875,
    lat: -22.9855,
    lng: -43.1929,
    address: 'Rua Bulhões de Carvalho, 61, Ipanema, Rio de Janeiro',
    reviewCount: 3903,
    facilities: ['ac', 'breakfast', 'pool', 'spa', 'wifi'],
  },

  alternatives: [
    {
      id: '10855699',
      name: 'Copa 6 P 3 q. 300 m praia Copa 800m Ipanema 1 vaga',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 26,
      pricePerNight: 131.74,
      totalPrice: 658.70,
      nights: 5,
      currency: 'EUR',
      address: '152 Rua Sá Ferreira',
      lat: -22.98138,
      lng: -43.19357,
      bookingUrl: 'https://www.booking.com/hotel/br/copacabana-4p-3q-300m-praia-copa-800m-ipanema-1-vaga.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 68,
      priceVsAnchor: -24.7,
      scoreVsAnchor: 0.2,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '11235291',
      name: 'Copacabana - Avenida Atlântica - Praia',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 38,
      pricePerNight: 156.10,
      totalPrice: 780.49,
      nights: 5,
      currency: 'EUR',
      address: '1230 Avenida Atlântica',
      lat: -22.96516,
      lng: -43.174976,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantica-vista-mar-rio-de-janeiro1.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 68,
      priceVsAnchor: -10.8,
      scoreVsAnchor: 0.6,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '14752',
      name: 'South American Copacabana Hotel',
      stars: 4,
      bookingScore: 8.3,
      reviewCount: 3446,
      pricePerNight: 171.84,
      totalPrice: 859.22,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Francisco Sá, 90',
      lat: -22.983539,
      lng: -43.193251,
      bookingUrl: 'https://www.booking.com/hotel/br/south-american-copacabana.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 68,
      priceVsAnchor: -1.8,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '1802378',
      name: 'ibis Copacabana Posto 5',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 2572,
      pricePerNight: 143.49,
      totalPrice: 717.47,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Xavier Da Silveira, 82',
      lat: -22.976329,
      lng: -43.191841,
      bookingUrl: 'https://www.booking.com/hotel/br/quarto-no-ibis-copacabana-posto-5.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: -18.0,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '252003',
      name: 'Mirador Rio Copacabana Hotel',
      stars: 4,
      bookingScore: 8.6,
      reviewCount: 4155,
      pricePerNight: 209.63,
      totalPrice: 1048.16,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Toneleros, 338',
      lat: -22.968605,
      lng: -43.189179,
      bookingUrl: 'https://www.booking.com/hotel/br/mirador-rio.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: 19.8,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1891329',
      name: 'Hotel Atlântico Travel Copacabana',
      stars: 4,
      bookingScore: 7.1,
      reviewCount: 10943,
      pricePerNight: 146.23,
      totalPrice: 731.15,
      nights: 5,
      currency: 'EUR',
      address: 'RUA BARATA RIBEIRO Nº 544',
      lat: -22.970787,
      lng: -43.188919,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantico-travel-copacabana.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 68,
      priceVsAnchor: -16.4,
      scoreVsAnchor: -1.5,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '258125',
      name: 'Hotel Atlantico Praia',
      stars: 4,
      bookingScore: 7.0,
      reviewCount: 4564,
      pricePerNight: 160.87,
      totalPrice: 804.37,
      nights: 5,
      currency: 'EUR',
      address: 'Avenida Atlantica, 1456',
      lat: -22.966327,
      lng: -43.176868,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantico-praia.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 68,
      priceVsAnchor: -8.1,
      scoreVsAnchor: -1.6,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '173056',
      name: 'Majestic Rio Palace Hotel',
      stars: 3,
      bookingScore: 7.7,
      reviewCount: 1167,
      pricePerNight: 158.81,
      totalPrice: 794.06,
      nights: 5,
      currency: 'EUR',
      address: 'Rua 5 de Julho, 195',
      lat: -22.971038,
      lng: -43.190214,
      bookingUrl: 'https://www.booking.com/hotel/br/majestic-rio-palace.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 68,
      priceVsAnchor: -9.3,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '23335',
      name: 'Hotel Bandeirantes',
      stars: 3,
      bookingScore: 7.8,
      reviewCount: 6946,
      pricePerNight: 178.08,
      totalPrice: 890.42,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Barata Ribeiro, 548',
      lat: -22.970833,
      lng: -43.188982,
      bookingUrl: 'https://www.booking.com/hotel/br/bandeirantes.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 55,
      anchorVfmScore: 68,
      priceVsAnchor: 1.8,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '11862',
      name: 'B&B HOTEL Rio Copacabana Posto 5',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 1681,
      pricePerNight: 214.27,
      totalPrice: 1071.33,
      nights: 5,
      currency: 'EUR',
      address: 'Av. Nossa Sra de Copacabana, 1256',
      lat: -22.982647,
      lng: -43.191094,
      bookingUrl: 'https://www.booking.com/hotel/br/copacabana-rio-rio-de-janeiro.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 54,
      anchorVfmScore: 68,
      priceVsAnchor: 22.4,
      scoreVsAnchor: -0.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
