/**
 * Données réelles Booking.com — Rio de Janeiro / Copacabana
 * Recherche MCP effectuée le 11/05/2026
 * Ancre : Atlantis Copacabana Hotel · 175 €/nuit · 4★ · note 8.6
 * Dates : 26/07/2026 → 31/07/2026 (5 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const RIO_RESULTS: SearchResults = {
  nights: 5,
  searchedAt: '2026-05-11T10:55:00Z',
  isMock: false,

  anchor: {
    name: 'Atlantis Copacabana Hotel',
    destination: 'Rio de Janeiro',
    checkinDate: '2026-07-26',
    checkoutDate: '2026-07-31',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/atlantis-copacabana.fr.html',
    pricePerNight: 175,
    currency: 'EUR',
    stars: 4,
    bookingScore: 8.6,
    services: [],
    // AnchorWithVFM extras
    vfmScore: 72,
    nights: 5,
    totalPrice: 875,
    lat: -22.9694,
    lng: -43.1768,
  },

  alternatives: [
    // — Sorted by VFM score desc —
    {
      id: '14752',
      name: 'South American Copacabana Hotel',
      stars: 4,
      bookingScore: 8.3,
      reviewCount: 3456,
      pricePerNight: 182.88,
      totalPrice: 914.40,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Francisco Sá, 90',
      lat: -22.983539,
      lng: -43.193251,
      bookingUrl: 'https://www.booking.com/hotel/br/south-american-copacabana.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 72,
      priceVsAnchor: 4.5,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '252003',
      name: 'Mirador Rio Copacabana Hotel',
      stars: 4,
      bookingScore: 8.6,
      reviewCount: 4138,
      pricePerNight: 214.29,
      totalPrice: 1071.47,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Toneleros, 338',
      lat: -22.968605,
      lng: -43.189179,
      bookingUrl: 'https://www.booking.com/hotel/br/mirador-rio.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 72,
      priceVsAnchor: 22.5,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '19402',
      name: 'Windsor Martinique Copacabana',
      stars: 3,
      bookingScore: 8.5,
      reviewCount: 2894,
      pricePerNight: 178.96,
      totalPrice: 894.82,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Sá Ferreira, 30',
      lat: -22.980693,
      lng: -43.190771,
      bookingUrl: 'https://www.booking.com/hotel/br/windsor-martinique.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 72,
      priceVsAnchor: 2.3,
      scoreVsAnchor: -0.1,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1891329',
      name: 'Hotel Atlântico Travel Copacabana',
      stars: 4,
      bookingScore: 7.1,
      reviewCount: 10931,
      pricePerNight: 149.48,
      totalPrice: 747.41,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Barata Ribeiro, 544',
      lat: -22.970787,
      lng: -43.188919,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantico-travel-copacabana.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 72,
      priceVsAnchor: -14.6,
      scoreVsAnchor: -1.5,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '402755',
      name: 'Windsor Copa Hotel',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 3030,
      pricePerNight: 200.0,
      totalPrice: 1000.01,
      nights: 5,
      currency: 'EUR',
      address: 'Av. Nossa Senhora de Copacabana, 335',
      lat: -22.967066,
      lng: -43.180137,
      bookingUrl: 'https://www.booking.com/hotel/br/windsor-copa.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'gym', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 57,
      anchorVfmScore: 72,
      priceVsAnchor: 14.3,
      scoreVsAnchor: 0.1,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '189005',
      name: 'Américas Benidorm Hotel',
      stars: 4,
      bookingScore: 7.9,
      reviewCount: 2529,
      pricePerNight: 198.10,
      totalPrice: 990.49,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Barata Ribeiro, 547',
      lat: -22.970898,
      lng: -43.188846,
      bookingUrl: 'https://www.booking.com/hotel/br/benidorm-palace.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 57,
      anchorVfmScore: 72,
      priceVsAnchor: 13.2,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '258125',
      name: 'Hotel Atlantico Praia',
      stars: 4,
      bookingScore: 7.0,
      reviewCount: 4573,
      pricePerNight: 164.45,
      totalPrice: 822.26,
      nights: 5,
      currency: 'EUR',
      address: 'Avenida Atlantica, 1456',
      lat: -22.966327,
      lng: -43.176868,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantico-praia.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 72,
      priceVsAnchor: -6.0,
      scoreVsAnchor: -1.6,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '23335',
      name: 'Hotel Bandeirantes',
      stars: 3,
      bookingScore: 7.8,
      reviewCount: 6937,
      pricePerNight: 182.04,
      totalPrice: 910.22,
      nights: 5,
      currency: 'EUR',
      address: 'Rua Barata Ribeiro, 548',
      lat: -22.970833,
      lng: -43.188982,
      bookingUrl: 'https://www.booking.com/hotel/br/bandeirantes.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 55,
      anchorVfmScore: 72,
      priceVsAnchor: 4.0,
      scoreVsAnchor: -0.8,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '11862',
      name: 'B&B HOTEL Rio Copacabana Posto 5',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 1683,
      pricePerNight: 212.11,
      totalPrice: 1060.56,
      nights: 5,
      currency: 'EUR',
      address: 'Av. Nossa Sra de Copacabana, 1256',
      lat: -22.982647,
      lng: -43.191094,
      bookingUrl: 'https://www.booking.com/hotel/br/copacabana-rio-rio-de-janeiro.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 54,
      anchorVfmScore: 72,
      priceVsAnchor: 21.2,
      scoreVsAnchor: -0.4,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
