/**
 * Données réelles Booking.com — Rio de Janeiro
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Atlantis Copacabana Hotel · 175 €/nuit · 3★ · note 8.6
 * Dates : 2026-07-26 → 2026-07-31 (5 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const RIO_RESULTS: SearchResults = {
  nights: 5,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Atlantis Copacabana Hotel',
    destination: 'Rio de Janeiro',
    checkinDate: '2026-07-26',
    checkoutDate: '2026-07-31',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/atlantis-copacabana.fr.html',
    pricePerNight: 175,
    currency: 'EUR',
    stars: 3,
    bookingScore: 8.6,
    services: [],
    vfmScore: 68,
    nights: 5,
    totalPrice: 875,
    lat: -22.9855,
    lng: -43.1929,
    address: 'Rua Bulhões de Carvalho, 61, Ipanema, Rio de Janeiro',
    reviewCount: 3903,
    facilities: ['ac', 'breakfast', 'pool', 'spa', 'wifi'],
  },

  alternatives: [
    {
      id: '11235291',
      name: 'Copacabana Avenida Atlântica',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 38,
      pricePerNight: 157.68,
      totalPrice: 788.41,
      nights: 5,
      currency: 'EUR',
      address: 'Zona Sul',
      lat: -22.96516,
      lng: -43.174976,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantica-vista-mar-rio-de-janeiro1.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 68,
      priceVsAnchor: -9.9,
      scoreVsAnchor: 0.6,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '189230',
      name: 'Américas Granada Hotel',
      stars: 4,
      bookingScore: 8.2,
      reviewCount: 5725,
      pricePerNight: 154.68,
      totalPrice: 773.42,
      nights: 5,
      currency: 'EUR',
      address: 'Lapa',
      lat: -22.911503,
      lng: -43.183526,
      bookingUrl: 'https://www.booking.com/hotel/br/americas-granada.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 68,
      priceVsAnchor: -11.6,
      scoreVsAnchor: -0.4,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '1415401',
      name: 'Windsor Oceanico Hotel',
      stars: 4,
      bookingScore: 8.8,
      reviewCount: 7337,
      pricePerNight: 196.72,
      totalPrice: 983.59,
      nights: 5,
      currency: 'EUR',
      address: 'Barra da Tijuca',
      lat: -23.011128,
      lng: -43.322081,
      bookingUrl: 'https://www.booking.com/hotel/br/windsor-oceanico.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 68,
      priceVsAnchor: 12.4,
      scoreVsAnchor: 0.2,
      starsVsAnchor: 1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1176769',
      name: 'Vila Galé Rio de Janeiro',
      stars: 4,
      bookingScore: 8.7,
      reviewCount: 7298,
      pricePerNight: 207.86,
      totalPrice: 1039.29,
      nights: 5,
      currency: 'EUR',
      address: 'Lapa',
      lat: -22.914596,
      lng: -43.184705,
      bookingUrl: 'https://www.booking.com/hotel/br/vila-gale-rio-de-janeiro.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: 18.8,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '252003',
      name: 'Mirador Rio Copacabana Hotel',
      stars: 4,
      bookingScore: 8.6,
      reviewCount: 4171,
      pricePerNight: 211.76,
      totalPrice: 1058.80,
      nights: 5,
      currency: 'EUR',
      address: 'Zona Sul',
      lat: -22.968605,
      lng: -43.189179,
      bookingUrl: 'https://www.booking.com/hotel/br/mirador-rio.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: 21.0,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '10973206',
      name: 'Vista deslumbrante Ipanema',
      stars: 4,
      bookingScore: 8.4,
      reviewCount: 106,
      pricePerNight: 195.05,
      totalPrice: 975.23,
      nights: 5,
      currency: 'EUR',
      address: 'Ipanema',
      lat: -22.983536,
      lng: -43.196982,
      bookingUrl: 'https://www.booking.com/hotel/br/vista-deslumbrante-ipanema.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: 11.5,
      scoreVsAnchor: -0.2,
      starsVsAnchor: 1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1802378',
      name: 'ibis Copacabana Posto 5',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 2568,
      pricePerNight: 145.53,
      totalPrice: 727.63,
      nights: 5,
      currency: 'EUR',
      address: 'Zona Sul',
      lat: -22.976329,
      lng: -43.191841,
      bookingUrl: 'https://www.booking.com/hotel/br/quarto-no-ibis-copacabana-posto-5.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: -16.8,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '2254252',
      name: 'ibis budget Botafogo',
      stars: 2,
      bookingScore: 7.9,
      reviewCount: 5699,
      pricePerNight: 121.66,
      totalPrice: 608.28,
      nights: 5,
      currency: 'EUR',
      address: 'Botafogo',
      lat: -22.945837,
      lng: -43.183876,
      bookingUrl: 'https://www.booking.com/hotel/br/ibis-budget-botafogo.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 68,
      priceVsAnchor: -30.5,
      scoreVsAnchor: -0.7,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '258125',
      name: 'Hotel Atlantico Praia',
      stars: 4,
      bookingScore: 7.0,
      reviewCount: 4569,
      pricePerNight: 162.51,
      totalPrice: 812.54,
      nights: 5,
      currency: 'EUR',
      address: 'Zona Sul',
      lat: -22.966327,
      lng: -43.176868,
      bookingUrl: 'https://www.booking.com/hotel/br/atlantico-praia.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 68,
      priceVsAnchor: -7.1,
      scoreVsAnchor: -1.6,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '16440279',
      name: 'Ipanema Postcard',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 188.53,
      totalPrice: 942.67,
      nights: 5,
      currency: 'EUR',
      address: 'Ipanema',
      lat: -22.985328,
      lng: -43.200217,
      bookingUrl: 'https://www.booking.com/hotel/br/ipanema-postcard.html?aid=8132308&checkin=2026-07-26&checkout=2026-07-31&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 68,
      priceVsAnchor: 7.7,
      scoreVsAnchor: -8.6,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
