/**
 * Données réelles Booking.com — Salvador de Bahia (arrivée 21/08)
 * Recherche MCP effectuée le 11/05/2026
 * Ancre : Bahiacafe Hotel · 244 €/nuit · 0★ · note 9.0
 * Dates : 21/08/2026 → 22/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const SALVADOR2_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-11T13:20:00Z',
  isMock: false,

  anchor: {
    name: 'Bahiacafe Hotel',
    destination: 'Salvador de Bahia',
    checkinDate: '2026-08-21',
    checkoutDate: '2026-08-22',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/bahiacafe.fr.html',
    pricePerNight: 244,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.0,
    services: [],
    vfmScore: 58,
    nights: 1,
    totalPrice: 244,
    lat: -12.974,
    lng: -38.508,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '1302198',
      name: 'Best Western Salvador Hangar',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 5343,
      pricePerNight: 108,
      totalPrice: 108,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Luis Viana Filho, 13145, Salvador (Aeroporto)',
      lat: -12.919785,
      lng: -38.354752,
      bookingUrl: 'https://www.booking.com/hotel/br/ibis-salvador-aeroporto-hangar.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 73,
      anchorVfmScore: 58,
      priceVsAnchor: -55.7,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '189007',
      name: 'Pousada Colonial Chile',
      stars: 3,
      bookingScore: 8.1,
      reviewCount: 2196,
      pricePerNight: 118,
      totalPrice: 118,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Chile, 07, Centro Histórico, Salvador',
      lat: -12.975592,
      lng: -38.513347,
      bookingUrl: 'https://www.booking.com/hotel/br/colonial-chile.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 71,
      anchorVfmScore: 58,
      priceVsAnchor: -51.6,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '191798',
      name: 'Hotel Deville Prime Salvador',
      stars: 5,
      bookingScore: 9.1,
      reviewCount: 1344,
      pricePerNight: 197,
      totalPrice: 197,
      nights: 1,
      currency: 'EUR',
      address: 'Ondina, Salvador',
      lat: -12.9840,
      lng: -38.5150,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=191798&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 70,
      anchorVfmScore: 58,
      priceVsAnchor: -19.3,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 5,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14783',
      name: 'Rede Andrade Barra',
      stars: 4,
      bookingScore: 7.1,
      reviewCount: 7136,
      pricePerNight: 103,
      totalPrice: 103,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Sete de Setembro, 3577, Barra, Salvador',
      lat: -13.002673,
      lng: -38.531978,
      bookingUrl: 'https://www.booking.com/hotel/br/sol-barra.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 70,
      anchorVfmScore: 58,
      priceVsAnchor: -57.8,
      scoreVsAnchor: -1.9,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '14878',
      name: 'Hotel Pousada da Mangueira',
      stars: 3,
      bookingScore: 8.9,
      reviewCount: 1597,
      pricePerNight: 153,
      totalPrice: 153,
      nights: 1,
      currency: 'EUR',
      address: 'Ladeira da Saúde, 09, Salvador',
      lat: -12.972531,
      lng: -38.50708,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-da-mangueira.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 69,
      anchorVfmScore: 58,
      priceVsAnchor: -37.3,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '878197',
      name: 'Wyndham Salvador Hangar',
      stars: 4,
      bookingScore: 8.5,
      reviewCount: 2237,
      pricePerNight: 179,
      totalPrice: 179,
      nights: 1,
      currency: 'EUR',
      address: 'Aeroporto, Salvador',
      lat: -12.9080,
      lng: -38.3310,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=878197&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 58,
      priceVsAnchor: -26.6,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '189008',
      name: 'Grande Hotel da Barra',
      stars: 4,
      bookingScore: 8.3,
      reviewCount: 2284,
      pricePerNight: 177,
      totalPrice: 177,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Forte São Diogo, 02, Barra, Salvador',
      lat: -13.002212,
      lng: -38.532477,
      bookingUrl: 'https://www.booking.com/hotel/br/grande-da-barra.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 58,
      priceVsAnchor: -27.5,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14093',
      name: 'Hotel Bahia do Sol',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 2678,
      pricePerNight: 176,
      totalPrice: 176,
      nights: 1,
      currency: 'EUR',
      address: 'Av. 7 de Setembro, 2009, Vitória, Salvador',
      lat: -12.991049,
      lng: -38.524933,
      bookingUrl: 'https://www.booking.com/hotel/br/bahia-do-sol.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 58,
      priceVsAnchor: -27.9,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '15569689',
      name: "Mart's Hotel",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 113,
      totalPrice: 113,
      nights: 1,
      currency: 'EUR',
      address: 'Salvador, Bahia',
      lat: -12.9760,
      lng: -38.5140,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel.html?hotel_id=15569689&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 30,
      anchorVfmScore: 58,
      priceVsAnchor: -53.7,
      scoreVsAnchor: -9.0,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '7555762',
      name: 'Pousada Beija Flor',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 128,
      totalPrice: 128,
      nights: 1,
      currency: 'EUR',
      address: '259 Rua Direita de Santo Antônio, Salvador',
      lat: -12.965862,
      lng: -38.505615,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-beija-flor-salvador.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 29,
      anchorVfmScore: 58,
      priceVsAnchor: -47.5,
      scoreVsAnchor: -9.0,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
  ],
};
