/**
 * Données réelles Booking.com — Salvador de Bahia (arrivée 21/08)
 * Recherche MCP effectuée le 13/05/2026
 * Ancre : Bahiacafe Hotel · 244 €/nuit · 0★ · note 9.0
 * Dates : 21/08/2026 → 22/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const SALVADOR2_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-13T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Bahiacafe Hotel',
    destination: 'Salvador de Bahia',
    checkinDate: '2026-08-21',
    checkoutDate: '2026-08-22',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/bahiacafe.fr.html',
    pricePerNight: 244,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.0,
    services: [],
    vfmScore: 58,
    nights: 1,
    totalPrice: 244,
    lat: -12.974,
    lng: -38.508,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '191798',
      name: 'Hotel Deville Prime Salvador',
      stars: 5,
      bookingScore: 9.0,
      reviewCount: 1348,
      pricePerNight: 197.05,
      totalPrice: 197.05,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Passargada, S/N, Itapuã, Salvador',
      lat: -12.950099,
      lng: -38.351198,
      bookingUrl: 'https://www.booking.com/hotel/br/deville-salvador.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 70,
      anchorVfmScore: 58,
      priceVsAnchor: -19.2,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 5,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '44534',
      name: 'CASA Di VINA Boutique Hotel',
      stars: 4,
      bookingScore: 9.1,
      reviewCount: 1898,
      pricePerNight: 190.41,
      totalPrice: 190.41,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Flamengo, 44, Farol de Itapua, Salvador',
      lat: -12.954442,
      lng: -38.352744,
      bookingUrl: 'https://www.booking.com/hotel/br/mar-brasil.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 58,
      priceVsAnchor: -22.0,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '285905',
      name: 'Casa Petunia Pousada Boutique',
      stars: 3,
      bookingScore: 9.2,
      reviewCount: 697,
      pricePerNight: 186.76,
      totalPrice: 186.76,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Engenheiro Milton Oliveira, 217, Barra, Salvador',
      lat: -13.007747,
      lng: -38.529267,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-petunia-pousada.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 58,
      priceVsAnchor: -23.5,
      scoreVsAnchor: 0.2,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14778',
      name: 'Gran Hotel Stella Maris Urban Resort',
      stars: 4,
      bookingScore: 8.3,
      reviewCount: 3687,
      pricePerNight: 192.62,
      totalPrice: 192.62,
      nights: 1,
      currency: 'EUR',
      address: 'Praca Stella Maris, 200, Stella Maris, Salvador',
      lat: -12.936461,
      lng: -38.328515,
      bookingUrl: 'https://www.booking.com/hotel/br/gran-stella-maris-resort-conventions.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 58,
      priceVsAnchor: -21.1,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14093',
      name: 'Hotel Bahia do Sol',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 2673,
      pricePerNight: 187.63,
      totalPrice: 187.63,
      nights: 1,
      currency: 'EUR',
      address: 'Av. 7 de Setembro, 2009, Vitoria, Salvador',
      lat: -12.991049,
      lng: -38.524933,
      bookingUrl: 'https://www.booking.com/hotel/br/bahia-do-sol.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 58,
      priceVsAnchor: -23.1,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '17854',
      name: 'Hotel Catharina Paraguaçu',
      stars: 3,
      bookingScore: 9.0,
      reviewCount: 1579,
      pricePerNight: 217.85,
      totalPrice: 217.85,
      nights: 1,
      currency: 'EUR',
      address: 'Rua João Gomes, 128, Rio Vermelho, Salvador',
      lat: -13.011964,
      lng: -38.491258,
      bookingUrl: 'https://www.booking.com/hotel/br/catharina-paraguacu.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 58,
      priceVsAnchor: -10.7,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '189007',
      name: 'Pousada Colonial Chile',
      stars: 3,
      bookingScore: 8.1,
      reviewCount: 2196,
      pricePerNight: 183.46,
      totalPrice: 183.46,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Chile, 07, Centro Histórico, Salvador',
      lat: -12.975592,
      lng: -38.513347,
      bookingUrl: 'https://www.booking.com/hotel/br/colonial-chile.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 58,
      priceVsAnchor: -24.8,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '14878',
      name: 'Hotel Pousada da Mangueira',
      stars: 3,
      bookingScore: 8.9,
      reviewCount: 1598,
      pricePerNight: 225.99,
      totalPrice: 225.99,
      nights: 1,
      currency: 'EUR',
      address: 'Ladeira da Saúde, 09, Salvador',
      lat: -12.972531,
      lng: -38.50708,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-da-mangueira.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 58,
      priceVsAnchor: -7.4,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '189029',
      name: 'Monte Pascoal Praia Hotel Salvador',
      stars: 4,
      bookingScore: 9.1,
      reviewCount: 1672,
      pricePerNight: 280.39,
      totalPrice: 280.39,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Oceânica, 591, Barra, Salvador',
      lat: -13.009008,
      lng: -38.526646,
      bookingUrl: 'https://www.booking.com/hotel/br/monte-pascoal-praia-salvador.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 58,
      priceVsAnchor: 14.9,
      scoreVsAnchor: 0.1,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '245534',
      name: 'Catussaba Resort Hotel',
      stars: 4,
      bookingScore: 8.0,
      reviewCount: 2968,
      pricePerNight: 258.28,
      totalPrice: 258.28,
      nights: 1,
      currency: 'EUR',
      address: 'Alameda Praia de Guarita, 07, Stella Maris, Salvador',
      lat: -12.946052,
      lng: -38.340416,
      bookingUrl: 'https://www.booking.com/hotel/br/catussaba-resort.html?aid=8132308&checkin=2026-08-21&checkout=2026-08-22&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 58,
      priceVsAnchor: 5.9,
      scoreVsAnchor: -1.0,
      starsVsAnchor: 4,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
