/**
 * Données réelles Booking.com — Salvador de Bahia (arrivée 17/08)
 * Recherche MCP effectuée le 14/05/2026
 * Ancre : Onda Azul · 78 €/nuit · 3★ · note 8.3
 * Dates : 2026-08-17 → 2026-08-18 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const SALVADOR1_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-14T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Onda Azul',
    destination: 'Salvador de Bahia',
    checkinDate: '2026-08-17',
    checkoutDate: '2026-08-18',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/onda-azul-valenca.fr.html',
    pricePerNight: 78,
    currency: 'EUR',
    stars: 3,
    bookingScore: 8.3,
    services: [],
    vfmScore: 67,
    nights: 1,
    totalPrice: 78,
    lat: -13.3732,
    lng: -39.0735,
    address: 'Rua Conselheiro Ferraz, S/nº Centro, Valença',
    reviewCount: 343,
    facilities: ['airport_shuttle', 'breakfast', 'parking', 'restaurant', 'wifi'],
  },

  alternatives: [
    {
      id: '15792050',
      name: 'Triplex Guaibim',
      stars: 3,
      bookingScore: 10.0,
      reviewCount: 2,
      pricePerNight: 86.45,
      totalPrice: 86.45,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Aloisio Evangelista da Fonseca',
      lat: -13.260475,
      lng: -38.958345,
      bookingUrl: 'https://www.booking.com/hotel/br/triplex-aconchegante-valenca.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 63,
      anchorVfmScore: 67,
      priceVsAnchor: 10.8,
      scoreVsAnchor: 1.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13430438',
      name: 'APARTAMENTO Village Daiane Taquary',
      stars: 3,
      bookingScore: 9.2,
      reviewCount: 4,
      pricePerNight: 83.45,
      totalPrice: 83.45,
      nights: 1,
      currency: 'EUR',
      address: 'Village Daiane Taquary 12',
      lat: -13.258311,
      lng: -38.957563,
      bookingUrl: 'https://www.booking.com/hotel/br/apt-near-tropical-beach-pine-forest-oasis-of-peace.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['parking', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 67,
      priceVsAnchor: 7.0,
      scoreVsAnchor: 0.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '10021079',
      name: 'Hotel e Restaurante Rio Mar',
      stars: 3,
      bookingScore: 7.3,
      reviewCount: 190,
      pricePerNight: 66.07,
      totalPrice: 66.07,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Dendezeiros, n 1000',
      lat: -13.365278,
      lng: -39.061831,
      bookingUrl: 'https://www.booking.com/hotel/br/e-restaurante-rio-mar.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 56,
      anchorVfmScore: 67,
      priceVsAnchor: -15.3,
      scoreVsAnchor: -1.0,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13712727',
      name: 'Hospedagem Clima Mar Guaibim',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 59.29,
      totalPrice: 59.29,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida taquary Guaibim',
      lat: -13.267741,
      lng: -38.958387,
      bookingUrl: 'https://www.booking.com/hotel/br/clima-mar.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 67,
      priceVsAnchor: -24.0,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '10249364',
      name: 'HOTEL RESTAURANTE E LANCHONETE PRIME',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 60.85,
      totalPrice: 60.85,
      nights: 1,
      currency: 'EUR',
      address: 'R MARQUES DO HERVAL, 95b',
      lat: -13.372373,
      lng: -39.073962,
      bookingUrl: 'https://www.booking.com/hotel/br/restaurante-e-lanchonete-prime.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 67,
      priceVsAnchor: -22.0,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '7387327',
      name: 'Estância Verde',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 81.37,
      totalPrice: 81.37,
      nights: 1,
      currency: 'EUR',
      address: '208 Rua do Pitanga',
      lat: -13.367275,
      lng: -39.081351,
      bookingUrl: 'https://www.booking.com/hotel/br/estancia-verde.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: [],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 67,
      priceVsAnchor: 4.3,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '14005283',
      name: "Cacao's Guaibim Residence",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 81.76,
      totalPrice: 81.76,
      nights: 1,
      currency: 'EUR',
      address: 'Tv. das Jangadas, 12',
      lat: -13.285918,
      lng: -38.966601,
      bookingUrl: 'https://www.booking.com/hotel/br/cacaos-guaibim-residence.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 67,
      priceVsAnchor: 4.8,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
  ],
};
