/**
 * Données réelles Booking.com — Salvador de Bahia (arrivée 17/08)
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Onda Azul · 78 €/nuit · 3★ · note 8.3
 * Dates : 2026-08-17 → 2026-08-18 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const SALVADOR1_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Onda Azul',
    destination: 'Salvador de Bahia',
    checkinDate: '2026-08-17',
    checkoutDate: '2026-08-18',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/onda-azul-valenca.fr.html',
    pricePerNight: 78,
    currency: 'EUR',
    stars: 3,
    bookingScore: 8.3,
    services: [],
    vfmScore: 67,
    nights: 1,
    totalPrice: 78,
    lat: -13.3732,
    lng: -39.0735,
    address: 'Rua Conselheiro Ferraz, S/nº Centro, Valença',
    reviewCount: 343,
    facilities: ['airport_shuttle', 'breakfast', 'parking', 'restaurant', 'wifi'],
  },

  alternatives: [
    {
      id: '7084899',
      name: 'Casas de Juan',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 448,
      pricePerNight: 54.98,
      totalPrice: 54.98,
      nights: 1,
      currency: 'EUR',
      address: '98 Rua da Prainha (Morro de São Paulo)',
      lat: -13.378792,
      lng: -38.914227,
      bookingUrl: 'https://www.booking.com/hotel/br/casas-de-juan.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 67,
      priceVsAnchor: -29.5,
      scoreVsAnchor: 0.4,
      starsVsAnchor: 0,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '13712727',
      name: 'Hospedagem Clima Mar Guaibim',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 50.34,
      totalPrice: 50.34,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida taquary Guaibim',
      lat: -13.267741,
      lng: -38.958387,
      bookingUrl: 'https://www.booking.com/hotel/br/clima-mar.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 23,
      anchorVfmScore: 67,
      priceVsAnchor: -35.5,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '7342868',
      name: 'Pousada Morro Tropical',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 55.43,
      totalPrice: 55.43,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Caminho da Praia 40 (Morro de São Paulo)',
      lat: -13.377917,
      lng: -38.915909,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-morro-tropical.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 21,
      anchorVfmScore: 67,
      priceVsAnchor: -28.9,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '10249364',
      name: 'HOTEL RESTAURANTE E LANCHONETE PRIME',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 59.99,
      totalPrice: 59.99,
      nights: 1,
      currency: 'EUR',
      address: 'R MARQUES DO HERVAL, 95b',
      lat: -13.372373,
      lng: -39.073962,
      bookingUrl: 'https://www.booking.com/hotel/br/restaurante-e-lanchonete-prime.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 67,
      priceVsAnchor: -23.1,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13403631',
      name: 'Villamar Pousada',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 79.83,
      totalPrice: 79.83,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Caminho da Praia (Morro de São Paulo)',
      lat: -13.377889,
      lng: -38.915823,
      bookingUrl: 'https://www.booking.com/hotel/br/villamar-pousada.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 67,
      priceVsAnchor: 2.3,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '7387327',
      name: 'Estância Verde',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 80.21,
      totalPrice: 80.21,
      nights: 1,
      currency: 'EUR',
      address: '208 Rua do Pitanga',
      lat: -13.367275,
      lng: -39.081351,
      bookingUrl: 'https://www.booking.com/hotel/br/estancia-verde.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 67,
      priceVsAnchor: 2.8,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '1034776',
      name: 'Brisa do Caitá Praia Hotel',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 86.71,
      totalPrice: 86.71,
      nights: 1,
      currency: 'EUR',
      address: 'Segunda Praia, s/n (Morro de São Paulo)',
      lat: -13.380409,
      lng: -38.911482,
      bookingUrl: 'https://www.booking.com/hotel/br/brisa-do-caita-praia-hotel.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 67,
      priceVsAnchor: 11.2,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '256637',
      name: 'Pousada Ilha da Saudade',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 91.82,
      totalPrice: 91.82,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Primeira Praia, s/n (Morro de São Paulo)',
      lat: -13.378314,
      lng: -38.914284,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-ilha-da-saudade.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 67,
      priceVsAnchor: 17.7,
      scoreVsAnchor: -8.3,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
  ],
};
