/**
 * Données réelles Booking.com — Salvador de Bahia (arrivée 17/08)
 * Recherche MCP effectuée le 13/05/2026
 * Ancre : Onda Azul · 78 €/nuit · 0★ · note 8.4
 * Dates : 17/08/2026 → 18/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const SALVADOR1_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-13T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Onda Azul',
    destination: 'Salvador de Bahia',
    checkinDate: '2026-08-17',
    checkoutDate: '2026-08-18',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/onda-azul-valenca.fr.html',
    pricePerNight: 78,
    currency: 'EUR',
    stars: 0,
    bookingScore: 8.4,
    services: [],
    vfmScore: 55,
    nights: 1,
    totalPrice: 78,
    lat: -12.975,
    lng: -38.513,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '10004215',
      name: 'Flat no Sol Vitoria Marina',
      stars: 4,
      bookingScore: 9.3,
      reviewCount: 209,
      pricePerNight: 59.59,
      totalPrice: 59.59,
      nights: 1,
      currency: 'EUR',
      address: '2068 Avenida Sete de Setembro Apto. 602, Barra, Salvador',
      lat: -12.997947,
      lng: -38.528091,
      bookingUrl: 'https://www.booking.com/hotel/br/flat-no-sol-vitoria-marina.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 69,
      anchorVfmScore: 55,
      priceVsAnchor: -23.6,
      scoreVsAnchor: 0.9,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '362077',
      name: 'Hotel Pousada Acácia da Barra',
      stars: 3,
      bookingScore: 9.1,
      reviewCount: 657,
      pricePerNight: 62.54,
      totalPrice: 62.54,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Engenheiro Milton Oliveira, 210, Barra, Salvador',
      lat: -13.007843,
      lng: -38.529219,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-aca-cia.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 55,
      priceVsAnchor: -19.8,
      scoreVsAnchor: 0.7,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '4476110',
      name: 'FAROL BEACH Suítes',
      stars: 3,
      bookingScore: 8.4,
      reviewCount: 1299,
      pricePerNight: 60.10,
      totalPrice: 60.10,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida das Dunas n.2, Itapuã, Salvador',
      lat: -12.955394,
      lng: -38.354321,
      bookingUrl: 'https://www.booking.com/hotel/br/residencial-da-jana.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 62,
      anchorVfmScore: 55,
      priceVsAnchor: -22.9,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '236948',
      name: 'Bed & Breakfast Villa Carmo',
      stars: 3,
      bookingScore: 8.6,
      reviewCount: 1971,
      pricePerNight: 69.49,
      totalPrice: 69.49,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Do Carmo, 58, Santo Antonio, Salvador',
      lat: -12.967891,
      lng: -38.507288,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-villa-carmo.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 55,
      priceVsAnchor: -10.9,
      scoreVsAnchor: 0.2,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '14783',
      name: 'Rede Andrade Barra',
      stars: 4,
      bookingScore: 7.1,
      reviewCount: 7141,
      pricePerNight: 63.50,
      totalPrice: 63.50,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Sete de Setembro, 3577, Barra, Salvador',
      lat: -13.002673,
      lng: -38.531978,
      bookingUrl: 'https://www.booking.com/hotel/br/sol-barra.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 55,
      priceVsAnchor: -18.6,
      scoreVsAnchor: -1.3,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '363020',
      name: 'Hotel Pousada Papaya Verde',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 59.07,
      totalPrice: 59.07,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Eng. Milton Oliveira, 177, Barra, Salvador',
      lat: -13.007817,
      lng: -38.529519,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-papaya-verde.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 55,
      priceVsAnchor: -24.3,
      scoreVsAnchor: -8.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '14991848',
      name: 'Pousada Solana',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 74.61,
      totalPrice: 74.61,
      nights: 1,
      currency: 'EUR',
      address: 'Alameda Antunes, 42, Barra, Salvador',
      lat: -13.003912,
      lng: -38.530057,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-solana.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 16,
      anchorVfmScore: 55,
      priceVsAnchor: -4.4,
      scoreVsAnchor: -8.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '306799',
      name: 'Pousada Stella Tropical',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 81.48,
      totalPrice: 81.48,
      nights: 1,
      currency: 'EUR',
      address: 'Rua Lídia Borja, 207, Stella Maris, Salvador',
      lat: -12.940735,
      lng: -38.333022,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-stella-tropical.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 55,
      priceVsAnchor: 4.5,
      scoreVsAnchor: -8.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '7555762',
      name: 'Pousada Beija Flor',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 92.00,
      totalPrice: 92.00,
      nights: 1,
      currency: 'EUR',
      address: '259 Rua Direita de Santo Antônio, Salvador',
      lat: -12.965862,
      lng: -38.505615,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-beija-flor-salvador.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 13,
      anchorVfmScore: 55,
      priceVsAnchor: 17.9,
      scoreVsAnchor: -8.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '15569689',
      name: "Mart's Hotel",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 95.55,
      totalPrice: 95.55,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Almirante Marques de Leão, 363, Barra, Salvador',
      lat: -13.008955,
      lng: -38.528788,
      bookingUrl: 'https://www.booking.com/hotel/br/marts.html?aid=8132308&checkin=2026-08-17&checkout=2026-08-18&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 12,
      anchorVfmScore: 55,
      priceVsAnchor: 22.5,
      scoreVsAnchor: -8.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
  ],
};
