/**
 * Données réelles Booking.com — São Luís
 * Recherche MCP effectuée le 13/05/2026
 * Ancre : Praiabella Hotel · 162 €/nuit · 0★ · note 8.7
 * Dates : 07/08/2026 → 08/08/2026 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts (calculateVFMScore / calculateAnchorVFM)
 */

import { SearchResults } from '@/lib/types';

export const SAO_LUIS_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-13T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Praiabella Hotel',
    destination: 'São Luís',
    checkinDate: '2026-08-07',
    checkoutDate: '2026-08-08',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/solare-praiabella.fr.html',
    pricePerNight: 162,
    currency: 'EUR',
    stars: 0,
    bookingScore: 8.7,
    services: [],
    vfmScore: 57,
    nights: 1,
    totalPrice: 162,
    lat: -2.491,
    lng: -44.261,
  },

  alternatives: [
    // — Triés par VFM score desc —
    {
      id: '1332119',
      name: 'Palma Hostel',
      stars: 4,
      bookingScore: 8.4,
      reviewCount: 582,
      pricePerNight: 125.08,
      totalPrice: 125.08,
      nights: 1,
      currency: 'EUR',
      address: 'Rua do Giz 129, Centro Histórico, São Luís',
      lat: -2.529669,
      lng: -44.304819,
      bookingUrl: 'https://www.booking.com/hotel/br/guest-house-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 57,
      priceVsAnchor: -22.8,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '1127338',
      name: 'Profissionalle Hotel São Luís',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 1282,
      pricePerNight: 123.80,
      totalPrice: 123.80,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Colares Moreira, Lote 13, QD 100, São Luís',
      lat: -2.504561,
      lng: -44.294171,
      bookingUrl: 'https://www.booking.com/hotel/br/profissionalle-hotel-saoluis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 57,
      priceVsAnchor: -23.6,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '364846',
      name: 'Rede Andrade SLZ',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 5489,
      pricePerNight: 126.26,
      totalPrice: 126.26,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Coronel Colares Moreira, Nro 14, Jardim Renascença, São Luís',
      lat: -2.503566,
      lng: -44.293135,
      bookingUrl: 'https://www.booking.com/hotel/br/nobile-inn-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 57,
      priceVsAnchor: -22.1,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '269940',
      name: 'Stop Way Hotel São Luís',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 2969,
      pricePerNight: 153.23,
      totalPrice: 153.23,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Mário Meirelles, Rua 26 - Quadra 20, São Luís',
      lat: -2.494687,
      lng: -44.305107,
      bookingUrl: 'https://www.booking.com/hotel/br/stop-way.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 57,
      priceVsAnchor: -5.4,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '9236606',
      name: 'Hotel Resort Rio Poty',
      stars: 4,
      bookingScore: 7.9,
      reviewCount: 2951,
      pricePerNight: 163.82,
      totalPrice: 163.82,
      nights: 1,
      currency: 'EUR',
      address: "Av. dos Holandeses, Lote 2/5, Quadra 32, Ponta d'Areia, São Luís",
      lat: -2.490799,
      lng: -44.30411,
      bookingUrl: 'https://www.booking.com/hotel/br/resort-rio-poty.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 57,
      priceVsAnchor: 1.1,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '271653',
      name: 'Litorânea Praia Hotel',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 3529,
      pricePerNight: 159.83,
      totalPrice: 159.83,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Litoranea 10 QD. 1 LOTE - Calhau, São Luís',
      lat: -2.483465,
      lng: -44.258656,
      bookingUrl: 'https://www.booking.com/hotel/br/litoranea-praia.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 57,
      anchorVfmScore: 57,
      priceVsAnchor: -1.3,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 3,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '2557278',
      name: 'Boulevard Park Hotel',
      stars: 2,
      bookingScore: 8.2,
      reviewCount: 1503,
      pricePerNight: 180.50,
      totalPrice: 180.50,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Guajajaras 1000, Jd Sao Cristovao, São Luís',
      lat: -2.571939,
      lng: -44.235276,
      bookingUrl: 'https://www.booking.com/hotel/br/boulevard-park-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 52,
      anchorVfmScore: 57,
      priceVsAnchor: 11.4,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 2,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '5964852',
      name: 'Pousada Litorânea',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 125.60,
      totalPrice: 125.60,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Litorânea 1983, São Luís',
      lat: -2.483684,
      lng: -44.252821,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-litoranea-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 57,
      priceVsAnchor: -22.5,
      scoreVsAnchor: -8.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '12729506',
      name: 'Casarão da Fonte',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 142.75,
      totalPrice: 142.75,
      nights: 1,
      currency: 'EUR',
      address: 'Rua dos Afogados, 221, São Luís',
      lat: -2.528084,
      lng: -44.301407,
      bookingUrl: 'https://www.booking.com/hotel/br/casarao-da-fonte-sao-luis2.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 57,
      priceVsAnchor: -11.9,
      scoreVsAnchor: -8.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '4382757',
      name: 'Mais Hotel Express',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 168.08,
      totalPrice: 168.08,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Três Nº13, Quadra 101, Jardim São Cristóvão, São Luís',
      lat: -2.575887,
      lng: -44.222796,
      bookingUrl: 'https://www.booking.com/hotel/br/mais-express.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 14,
      anchorVfmScore: 57,
      priceVsAnchor: 3.8,
      scoreVsAnchor: -8.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
