/**
 * Données réelles Booking.com — São Luís
 * Recherche MCP effectuée le 04/07/2026
 * Ancre : Praiabella Hotel · 162 €/nuit · 3★ · note 8.7
 * Dates : 2026-08-07 → 2026-08-08 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const SAO_LUIS_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-07-04T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Praiabella Hotel',
    destination: 'São Luís',
    checkinDate: '2026-08-07',
    checkoutDate: '2026-08-08',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/solare-praiabella.fr.html',
    pricePerNight: 162,
    currency: 'EUR',
    stars: 3,
    bookingScore: 8.7,
    services: [],
    vfmScore: 69,
    nights: 1,
    totalPrice: 162,
    lat: -2.484572,
    lng: -44.26328,
    address: 'Avenida Litorânea, São Luís',
    reviewCount: 1519,
    facilities: ['ac', 'pool', 'restaurant', 'sea_view', 'wifi'],
  },

  alternatives: [
    {
      id: '269940',
      name: 'Stop Way Hotel São Luís',
      stars: 3,
      bookingScore: 8.6,
      reviewCount: 2826,
      pricePerNight: 83.38,
      totalPrice: 83.38,
      nights: 1,
      currency: 'EUR',
      address: 'Av Mário Meirelles Rua 26',
      lat: -2.494687,
      lng: -44.305107,
      bookingUrl: 'https://www.booking.com/hotel/br/stop-way.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 73,
      anchorVfmScore: 69,
      priceVsAnchor: -49,
      scoreVsAnchor: -0.1,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '13305968',
      name: 'Apartamento Vista Mar',
      stars: 3,
      bookingScore: 9.4,
      reviewCount: 59,
      pricePerNight: 94.14,
      totalPrice: 94.14,
      nights: 1,
      currency: 'EUR',
      address: 'São Luís, Maranhão',
      lat: -2.497263,
      lng: -44.307808,
      bookingUrl: 'https://www.booking.com/hotel/br/apartamento-de-frente-para-o-mar-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi', 'pool', 'sea_view', 'parking'],
      isAvailable: true,
      vfmScore: 72,
      anchorVfmScore: 69,
      priceVsAnchor: -42,
      scoreVsAnchor: 0.7,
      starsVsAnchor: 0,
      isBetterDeal: true,
      priceCategory: 'excellent',
    },
    {
      id: '299287',
      name: 'Costa Atlantico Hotel',
      stars: 3,
      bookingScore: 8.3,
      reviewCount: 837,
      pricePerNight: 80.26,
      totalPrice: 80.26,
      nights: 1,
      currency: 'EUR',
      address: 'Av Sambaquis, 35',
      lat: -2.491437,
      lng: -44.28254,
      bookingUrl: 'https://www.booking.com/hotel/br/costa-atlantico.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 72,
      anchorVfmScore: 69,
      priceVsAnchor: -51,
      scoreVsAnchor: -0.4,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '1127338',
      name: 'Profissionalle Hotel São Luís',
      stars: 3,
      bookingScore: 8.1,
      reviewCount: 1335,
      pricePerNight: 80.39,
      totalPrice: 80.39,
      nights: 1,
      currency: 'EUR',
      address: 'Av Colares Moreira Lote 13',
      lat: -2.504561,
      lng: -44.294171,
      bookingUrl: 'https://www.booking.com/hotel/br/profissionalle-hotel-saoluis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 71,
      anchorVfmScore: 69,
      priceVsAnchor: -50,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '97456',
      name: 'Abbeville Hotel Torre I-II',
      stars: 3,
      bookingScore: 8.1,
      reviewCount: 2613,
      pricePerNight: 80.26,
      totalPrice: 80.26,
      nights: 1,
      currency: 'EUR',
      address: 'Av São Luís',
      lat: -2.512119,
      lng: -44.303664,
      bookingUrl: 'https://www.booking.com/hotel/br/abbeville-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'gym'],
      isAvailable: true,
      vfmScore: 71,
      anchorVfmScore: 69,
      priceVsAnchor: -51,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'excellent',
    },
    {
      id: '176072',
      name: 'Hotel Luzeiros São Luis',
      stars: 5,
      bookingScore: 9.0,
      reviewCount: 5113,
      pricePerNight: 135.17,
      totalPrice: 135.17,
      nights: 1,
      currency: 'EUR',
      address: 'Av dos Holandeses, São Luís',
      lat: -2.487785,
      lng: -44.297829,
      bookingUrl: 'https://www.booking.com/hotel/br/luzeiros-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'pool', 'spa', 'gym'],
      isAvailable: true,
      vfmScore: 69,
      anchorVfmScore: 69,
      priceVsAnchor: -17,
      scoreVsAnchor: 0.3,
      starsVsAnchor: 2,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '239631',
      name: 'Brisamar Hotel & SPA São Luís',
      stars: 4,
      bookingScore: 9.0,
      reviewCount: 3133,
      pricePerNight: 121.65,
      totalPrice: 121.65,
      nights: 1,
      currency: 'EUR',
      address: 'Av dos Holandeses, São Luís',
      lat: -2.49096,
      lng: -44.305447,
      bookingUrl: 'https://www.booking.com/hotel/br/brisamar.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'pool', 'spa', 'sea_view', 'parking'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 69,
      priceVsAnchor: -25,
      scoreVsAnchor: 0.3,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '364846',
      name: 'Rede Andrade SLZ',
      stars: 3,
      bookingScore: 8.0,
      reviewCount: 5872,
      pricePerNight: 120.07,
      totalPrice: 120.07,
      nights: 1,
      currency: 'EUR',
      address: 'Av Coronel Colares Moreira 14',
      lat: -2.503566,
      lng: -44.293135,
      bookingUrl: 'https://www.booking.com/hotel/br/nobile-inn-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 69,
      priceVsAnchor: -26,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
  ],
};
