/**
 * Données réelles Booking.com — São Luís
 * Recherche MCP effectuée le 16/05/2026
 * Ancre : Praiabella Hotel · 162 €/nuit · 3★ · note 8.7
 * Dates : 2026-08-07 → 2026-08-08 (1 nuit) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const SAO_LUIS_RESULTS: SearchResults = {
  nights: 1,
  searchedAt: '2026-05-16T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Praiabella Hotel',
    destination: 'São Luís',
    checkinDate: '2026-08-07',
    checkoutDate: '2026-08-08',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/solare-praiabella.fr.html',
    pricePerNight: 162,
    currency: 'EUR',
    stars: 3,
    bookingScore: 8.7,
    services: [],
    vfmScore: 69,
    nights: 1,
    totalPrice: 162,
    lat: -2.484572,
    lng: -44.26328,
    address: 'Avenida Litorânea, São Luís',
    reviewCount: 1519,
    facilities: ['ac', 'pool', 'restaurant', 'sea_view', 'wifi'],
  },

  alternatives: [
    {
      id: '1332119',
      name: 'Palma Hostel',
      stars: 4,
      bookingScore: 8.4,
      reviewCount: 583,
      pricePerNight: 122.16,
      totalPrice: 122.16,
      nights: 1,
      currency: 'EUR',
      address: 'Rua do Giz 129',
      lat: -2.529669,
      lng: -44.304819,
      bookingUrl: 'https://www.booking.com/hotel/br/guest-house-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['airport_shuttle', 'wifi'],
      isAvailable: true,
      vfmScore: 65,
      anchorVfmScore: 69,
      priceVsAnchor: -24.6,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'good',
    },
    {
      id: '1127338',
      name: 'Profissionalle Hotel São Luís',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 1284,
      pricePerNight: 127.15,
      totalPrice: 127.15,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Colares Moreira, Lote 13, QD 100',
      lat: -2.504561,
      lng: -44.294171,
      bookingUrl: 'https://www.booking.com/hotel/br/profissionalle-hotel-saoluis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 61,
      anchorVfmScore: 69,
      priceVsAnchor: -21.5,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '269940',
      name: 'Stop Way Hotel São Luís',
      stars: 3,
      bookingScore: 8.7,
      reviewCount: 2966,
      pricePerNight: 149.65,
      totalPrice: 149.65,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Mário Meirelles, Rua 26 - Quadra 20 - Lotes 06 E 08',
      lat: -2.494687,
      lng: -44.305107,
      bookingUrl: 'https://www.booking.com/hotel/br/stop-way.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 69,
      priceVsAnchor: -7.6,
      scoreVsAnchor: 0.0,
      starsVsAnchor: 0,
      isBetterDeal: true,
      priceCategory: 'high',
    },
    {
      id: '364846',
      name: 'Rede Andrade SLZ',
      stars: 3,
      bookingScore: 7.9,
      reviewCount: 5513,
      pricePerNight: 123.31,
      totalPrice: 123.31,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Coronel Colares Moreira, Nro 14 - Quadra 100',
      lat: -2.503566,
      lng: -44.293135,
      bookingUrl: 'https://www.booking.com/hotel/br/nobile-inn-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 60,
      anchorVfmScore: 69,
      priceVsAnchor: -23.9,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '9236606',
      name: 'Hotel Resort Rio Poty',
      stars: 4,
      bookingScore: 7.9,
      reviewCount: 2952,
      pricePerNight: 160.00,
      totalPrice: 160.00,
      nights: 1,
      currency: 'EUR',
      address: 'AVENIDA DOS HOLANDESES, LOTE 2/5 QUADRA 32 Nº 1',
      lat: -2.490799,
      lng: -44.30411,
      bookingUrl: 'https://www.booking.com/hotel/br/resort-rio-poty.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 59,
      anchorVfmScore: 69,
      priceVsAnchor: -1.2,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 1,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '271653',
      name: 'Litorânea Praia Hotel',
      stars: 3,
      bookingScore: 8.2,
      reviewCount: 3530,
      pricePerNight: 156.10,
      totalPrice: 156.10,
      nights: 1,
      currency: 'EUR',
      address: 'Av. Litoranea 10 QD. 1 LOTE - Calhau',
      lat: -2.483465,
      lng: -44.258656,
      bookingUrl: 'https://www.booking.com/hotel/br/litoranea-praia.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 57,
      anchorVfmScore: 69,
      priceVsAnchor: -3.6,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '2557278',
      name: 'Boulevard Park Hotel',
      stars: 2,
      bookingScore: 8.3,
      reviewCount: 1504,
      pricePerNight: 176.29,
      totalPrice: 176.29,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Guajajaras 1000 Jd Sao Cristovao',
      lat: -2.571939,
      lng: -44.235276,
      bookingUrl: 'https://www.booking.com/hotel/br/boulevard-park-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 53,
      anchorVfmScore: 69,
      priceVsAnchor: 8.8,
      scoreVsAnchor: -0.4,
      starsVsAnchor: -1,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '5964852',
      name: 'Pousada Litorânea',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 122.67,
      totalPrice: 122.67,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Litorânea 1983',
      lat: -2.483684,
      lng: -44.252821,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-litoranea-sao-luis.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['parking', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 69,
      priceVsAnchor: -24.3,
      scoreVsAnchor: -8.7,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'good',
    },
    {
      id: '12729506',
      name: 'Casarão da Fonte',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 139.42,
      totalPrice: 139.42,
      nights: 1,
      currency: 'EUR',
      address: 'Rua dos Afogados, 221',
      lat: -2.528084,
      lng: -44.301407,
      bookingUrl: 'https://www.booking.com/hotel/br/casarao-da-fonte-sao-luis2.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['pool', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 69,
      priceVsAnchor: -13.9,
      scoreVsAnchor: -8.7,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'high',
    },
    {
      id: '4382757',
      name: 'Mais Hotel Express',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 164.16,
      totalPrice: 164.16,
      nights: 1,
      currency: 'EUR',
      address: 'Avenida Três Nº13, Quadra 101 - Jardim São Cristóvão',
      lat: -2.575887,
      lng: -44.222796,
      bookingUrl: 'https://www.booking.com/hotel/br/mais-express.html?aid=8132308&checkin=2026-08-07&checkout=2026-08-08&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'parking', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 69,
      priceVsAnchor: 1.3,
      scoreVsAnchor: -8.7,
      starsVsAnchor: -3,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
