/**
 * Données réelles Booking.com — Trancoso, Bahia
 * Recherche MCP effectuée le 19/05/2026
 * Ancre : Pousada Quarto Crescente · 249 €/nuit · 0★ · note 9.9
 * Dates : 2026-07-31 → 2026-08-03 (3 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const TRANCOSO_RESULTS: SearchResults = {
  nights: 3,
  searchedAt: '2026-05-19T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pousada Quarto Crescente',
    destination: 'Trancoso',
    checkinDate: '2026-07-31',
    checkoutDate: '2026-08-03',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-quarto-crescente-trancoso.fr.html',
    pricePerNight: 249,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.9,
    services: [],
    vfmScore: 62,
    nights: 3,
    totalPrice: 747,
    lat: -16.591,
    lng: -39.101,
    address: 'Trancoso, Bahia',
    reviewCount: 0,
    facilities: ['pool', 'wifi'],
  },

  alternatives: [
    {
      id: '11161032',
      name: 'Casa Terravista Trancoso',
      stars: 4,
      bookingScore: 9.0,
      reviewCount: 10,
      pricePerNight: 198.82,
      totalPrice: 596.45,
      nights: 3,
      currency: 'EUR',
      address: 'Estrada Municipal de Trancoso, Km 18',
      lat: -16.552415,
      lng: -39.090328,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-terravista-trancoso.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'gym', 'parking', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 67,
      anchorVfmScore: 62,
      priceVsAnchor: -20.2,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '429396',
      name: 'Pousada Seis e Meia',
      stars: 4,
      bookingScore: 9.2,
      reviewCount: 256,
      pricePerNight: 247.17,
      totalPrice: 741.50,
      nights: 3,
      currency: 'EUR',
      address: 'Avenida Principal, 275',
      lat: -16.590383,
      lng: -39.100249,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-seis-e-meia.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 64,
      anchorVfmScore: 62,
      priceVsAnchor: -0.7,
      scoreVsAnchor: -0.7,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '843264',
      name: 'Pousada Hibisco',
      stars: 3,
      bookingScore: 9.0,
      reviewCount: 82,
      pricePerNight: 286.30,
      totalPrice: 858.89,
      nights: 3,
      currency: 'EUR',
      address: 'Rua Bom Jesus, s/n',
      lat: -16.587826,
      lng: -39.097095,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-hibisco-trancoso.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 58,
      anchorVfmScore: 62,
      priceVsAnchor: 15.0,
      scoreVsAnchor: -0.9,
      starsVsAnchor: 3,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '258315',
      name: 'Pousada do Bosque',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 188.72,
      totalPrice: 566.17,
      nights: 3,
      currency: 'EUR',
      address: 'Rua da Cuba, nº 1 - Centro',
      lat: -16.591374,
      lng: -39.096241,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-do-bosque.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'parking', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 62,
      priceVsAnchor: -24.2,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '4756362',
      name: 'Travel Inn Pousadas & Beach Club',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 187.85,
      totalPrice: 563.54,
      nights: 3,
      currency: 'EUR',
      address: 'Estrada de Itaquena, 740',
      lat: -16.606842,
      lng: -39.094976,
      bookingUrl: 'https://www.booking.com/hotel/br/travel-inn-trancoso-suites.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'sea_view', 'wifi'],
      isAvailable: true,
      vfmScore: 20,
      anchorVfmScore: 62,
      priceVsAnchor: -24.6,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '575107',
      name: 'Pousada Jequitibá',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 195.39,
      totalPrice: 586.17,
      nights: 3,
      currency: 'EUR',
      address: 'Rua do Bosque, s/n',
      lat: -16.590399,
      lng: -39.095857,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-jequitiba.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'wifi'],
      isAvailable: true,
      vfmScore: 19,
      anchorVfmScore: 62,
      priceVsAnchor: -21.5,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '333108',
      name: "Mata N'ativa Pousada",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 215.96,
      totalPrice: 647.87,
      nights: 3,
      currency: 'EUR',
      address: 'Estrada para Arraial, s/n',
      lat: -16.586382,
      lng: -39.094261,
      bookingUrl: 'https://www.booking.com/hotel/br/mata-na-ativa-pousada.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 17,
      anchorVfmScore: 62,
      priceVsAnchor: -13.3,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1134554',
      name: 'Pousada Le Refuge',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 254.35,
      totalPrice: 763.05,
      nights: 3,
      currency: 'EUR',
      address: 'Caminho da Praia, s/n',
      lat: -16.592412,
      lng: -39.0913,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-le-refuge-trancoso.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 62,
      priceVsAnchor: 2.1,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '1283028',
      name: 'Casa da Glória Trancoso',
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 248.86,
      totalPrice: 746.59,
      nights: 3,
      currency: 'EUR',
      address: 'Praca do Quadrado, s/n',
      lat: -16.589525,
      lng: -39.09454,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-da-gloria-trancoso.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'pool', 'restaurant', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 62,
      priceVsAnchor: -0.1,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
    {
      id: '353801',
      name: "D'amo Hotel Boutique",
      stars: 0,
      bookingScore: 0,
      reviewCount: 0,
      pricePerNight: 245.89,
      totalPrice: 737.67,
      nights: 3,
      currency: 'EUR',
      address: 'Avenida Itabela, 41',
      lat: -16.591431,
      lng: -39.101702,
      bookingUrl: 'https://www.booking.com/hotel/br/pousada-recanto-do-sol.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=3&group_children=1&age=15&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'airport_shuttle', 'gym', 'pool', 'spa', 'wifi'],
      isAvailable: true,
      vfmScore: 15,
      anchorVfmScore: 62,
      priceVsAnchor: -1.2,
      scoreVsAnchor: -9.9,
      starsVsAnchor: 0,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
