/**
 * Données réelles Booking.com — Trancoso, Bahia
 * Recherche MCP effectuée le 04/07/2026
 * Ancre : Pousada Quarto Crescente · 249 €/nuit · 0★ · note 9.9
 * Dates : 2026-07-31 → 2026-08-03 (3 nuits) · 3 adultes + 1 enfant (15 ans) · ±25 %
 * VFM calculé avec la formule exacte de lib/vfm.ts
 */

import { SearchResults } from '@/lib/types';

export const TRANCOSO_RESULTS: SearchResults = {
  nights: 3,
  searchedAt: '2026-07-04T10:00:00Z',
  isMock: false,

  anchor: {
    name: 'Pousada Quarto Crescente',
    destination: 'Trancoso',
    checkinDate: '2026-07-31',
    checkoutDate: '2026-08-03',
    adults: 3,
    children: [15],
    bookingUrl: 'https://www.booking.com/hotel/br/pousada-quarto-crescente-trancoso.fr.html',
    pricePerNight: 249,
    currency: 'EUR',
    stars: 0,
    bookingScore: 9.9,
    services: [],
    vfmScore: 62,
    nights: 3,
    totalPrice: 747,
    lat: -16.591,
    lng: -39.101,
    address: 'Trancoso, Bahia',
    reviewCount: 0,
    facilities: ['pool', 'wifi'],
  },

  alternatives: [
    {
      id: '1469972',
      name: 'Hotel Boutique Perainda',
      stars: 5,
      bookingScore: 9.6,
      reviewCount: 78,
      pricePerNight: 225.91,
      totalPrice: 677.74,
      nights: 3,
      currency: 'EUR',
      address: 'Trancoso, Bahia',
      lat: -16.587874,
      lng: -39.099464,
      bookingUrl: 'https://www.booking.com/hotel/br/casa-de-perainda.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'pool', 'spa', 'parking'],
      isAvailable: true,
      vfmScore: 70,
      anchorVfmScore: 62,
      priceVsAnchor: -9,
      scoreVsAnchor: -0.3,
      starsVsAnchor: 5,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '335917',
      name: 'Soleluna Casa Pousada',
      stars: 5,
      bookingScore: 9.4,
      reviewCount: 472,
      pricePerNight: 210.14,
      totalPrice: 630.41,
      nights: 3,
      currency: 'EUR',
      address: 'Trancoso, Bahia',
      lat: -16.592474,
      lng: -39.099057,
      bookingUrl: 'https://www.booking.com/hotel/br/soleluna-casa-pousada.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'pool', 'spa', 'parking'],
      isAvailable: true,
      vfmScore: 70,
      anchorVfmScore: 62,
      priceVsAnchor: -16,
      scoreVsAnchor: -0.5,
      starsVsAnchor: 5,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '11076142',
      name: 'AWÊ Villa Boutique & Beach Club',
      stars: 4,
      bookingScore: 9.1,
      reviewCount: 95,
      pricePerNight: 189.22,
      totalPrice: 567.66,
      nights: 3,
      currency: 'EUR',
      address: 'Trancoso, Bahia',
      lat: -16.587449,
      lng: -39.090721,
      bookingUrl: 'https://www.booking.com/hotel/br/awe-villa-boutique.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'pool', 'parking'],
      isAvailable: true,
      vfmScore: 68,
      anchorVfmScore: 62,
      priceVsAnchor: -24,
      scoreVsAnchor: -0.8,
      starsVsAnchor: 4,
      isBetterDeal: true,
      priceCategory: 'premium',
    },
    {
      id: '402621',
      name: 'Hotel Boutique Bahia Bonita',
      stars: 5,
      bookingScore: 9.3,
      reviewCount: 247,
      pricePerNight: 269.08,
      totalPrice: 807.23,
      nights: 3,
      currency: 'EUR',
      address: 'Trancoso, Bahia',
      lat: -16.588132,
      lng: -39.095541,
      bookingUrl: 'https://www.booking.com/hotel/br/hotel-bahia-bonita.html?aid=8132308&checkin=2026-07-31&checkout=2026-08-03&no_rooms=1&group_adults=2&selected_currency=EUR',
      imageUrl: '',
      facilities: ['ac', 'restaurant', 'wifi', 'pool', 'parking'],
      isAvailable: true,
      vfmScore: 66,
      anchorVfmScore: 62,
      priceVsAnchor: 8,
      scoreVsAnchor: -0.6,
      starsVsAnchor: 5,
      isBetterDeal: false,
      priceCategory: 'premium',
    },
  ],
};
